using System;
using System.Net;
using System.Net.Http;
using System.Security.Cryptography.X509Certificates;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Digipost.Api.Client.Common;
using Microsoft.Extensions.Logging;
using Org.BouncyCastle.Crypto;
using Org.BouncyCastle.Security;

namespace Digipost.Api.Client.Internal
{
    internal class AuthenticationHandler : DelegatingHandler
    {
        private static ILogger<DigipostClient> _logger;

        public AuthenticationHandler(ClientConfig clientConfig, X509Certificate2 businessCertificate, ILoggerFactory loggerFactory)
        {
            _logger = loggerFactory.CreateLogger<DigipostClient>();
            ClientConfig = clientConfig;
            BusinessCertificate = businessCertificate;
            Method = WebRequestMethods.Http.Get;
        }

        private ClientConfig ClientConfig { get; }

        private X509Certificate2 BusinessCertificate { get; }

        private string Method { get; set; }

        protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        {
            var date = RequestHeaderUtility.ApplyCommonHeaders(request, ClientConfig.Broker.Id);
            var brokerId = ClientConfig.Broker.Id.ToString();

            Method = request.Method.ToString();

            var contentHash = await RequestHeaderUtility.ApplyContentHashHeaderIfPresent(request).ConfigureAwait(false);

            var signature = ComputeSignature(Method, request.RequestUri, date, contentHash, brokerId, BusinessCertificate, ClientConfig.LogRequestAndResponse);
            request.Headers.Add("X-Digipost-Signature", signature);

            return await base.SendAsync(request, cancellationToken).ConfigureAwait(false);
        }

        internal static string ComputeSignature(string method, Uri uri, string date, string contentSha256Hash,
            string userId, X509Certificate2 businessCertificate, bool logRequestAndResponse)
        {
            var uriParts = new UriParts(uri);

            if (logRequestAndResponse)
            {
                _logger.LogDebug("Compute signature, canonical string generated by .NET Client:");
                _logger.LogDebug("=== SIGNATURE DATA START===");
            }

            string messageHeader;

            if (contentSha256Hash != null)
            {
                messageHeader = method.ToUpper() + "\n" +
                                uriParts.AbsoluteUri + "\n" +
                                "date: " + date + "\n" +
                                "x-content-sha256: " + contentSha256Hash + "\n" +
                                "x-digipost-userid: " + userId + "\n" +
                                uriParts.Parameters.ToLower() + "\n";
            }
            else
            {
                messageHeader = method.ToUpper() + "\n" +
                                uriParts.AbsoluteUri + "\n" +
                                "date: " + date + "\n" +
                                "x-digipost-userid: " + userId + "\n" +
                                uriParts.Parameters.ToLower() + "\n";
            }

            if (logRequestAndResponse)
            {
                _logger.LogDebug(messageHeader);
                _logger.LogDebug("=== SIGNATURE DATA END ===");
            }

            byte[] messageBytes = Encoding.UTF8.GetBytes(messageHeader);


            var privKey = DotNetUtilities.GetRsaKeyPair(businessCertificate.GetRSAPrivateKey());

            ISigner signer = SignerUtilities.GetSigner("SHA-256withRSA");
            signer.Init(true, privKey.Private);
            signer.BlockUpdate(messageBytes, 0, messageBytes.Length);

            var base64Signature = Convert.ToBase64String(signer.GenerateSignature());

            return base64Signature;
        }

        private class UriParts
        {
            public UriParts(Uri uri)
            {
                var datUri = uri.IsAbsoluteUri ? uri.AbsolutePath : "/" + uri.OriginalString;
                AbsoluteUri = datUri.ToLower();
                Parameters = uri.Query.Length > 0 ? uri.Query.Substring(1) : "";
            }

            public string AbsoluteUri { get; }

            public string Parameters { get; }
        }
    }
}
