//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.0.0.
namespace DataTypes
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("address", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Address
    {
        
        [System.Xml.Serialization.XmlElementAttribute("street-address", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Street_Address { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("street-address-2", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Street_Address_2 { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("postal-code", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Postal_Code { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("city", Namespace="http://api.digipost.no/schema/datatypes")]
        public string City { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("country", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Country { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("appointment", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("appointment", Namespace="http://api.digipost.no/schema/datatypes")]
    public partial class Appointment
    {
        
        [System.Xml.Serialization.XmlElementAttribute("start-time", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Start_Time { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("end-time", Namespace="http://api.digipost.no/schema/datatypes")]
        public string End_Time { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("arrival-time", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Arrival_Time { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("place", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Place { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("address", Namespace="http://api.digipost.no/schema/datatypes")]
        public Address Address { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("sub-title", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Sub_Title { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Info> _info;
        
        [System.Xml.Serialization.XmlElementAttribute("info", Namespace="http://api.digipost.no/schema/datatypes")]
        public System.Collections.ObjectModel.Collection<Info> Info
        {
            get
            {
                return this._info;
            }
            private set
            {
                this._info = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InfoSpecified
        {
            get
            {
                return (this.Info.Count != 0);
            }
        }
        
        public Appointment()
        {
            this._info = new System.Collections.ObjectModel.Collection<Info>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("info", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Info
    {
        
        [System.Xml.Serialization.XmlElementAttribute("title", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Title { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("text", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Text { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("barcode", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Barcode
    {
        
        [System.Xml.Serialization.XmlElementAttribute("barcode-value", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Barcode_Value { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("barcode-type", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Barcode_Type { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("barcode-text", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Barcode_Text { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool _show_Value_In_Barcode = false;
        
        [System.ComponentModel.DefaultValueAttribute(false)]
        [System.Xml.Serialization.XmlElementAttribute("show-value-in-barcode", Namespace="http://api.digipost.no/schema/datatypes")]
        public bool Show_Value_In_Barcode
        {
            get
            {
                return this._show_Value_In_Barcode;
            }
            set
            {
                this._show_Value_In_Barcode = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("boligdetaljer", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("boligdetaljer", Namespace="http://api.digipost.no/schema/datatypes")]
    public partial class Boligdetaljer
    {
        
        [System.Xml.Serialization.XmlElementAttribute("residence", Namespace="http://api.digipost.no/schema/datatypes")]
        public Residence Residence { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Hjemmelshaver> _hjemmelshavere;
        
        [System.Xml.Serialization.XmlElementAttribute("hjemmelshavere", Namespace="http://api.digipost.no/schema/datatypes")]
        public System.Collections.ObjectModel.Collection<Hjemmelshaver> Hjemmelshavere
        {
            get
            {
                return this._hjemmelshavere;
            }
            private set
            {
                this._hjemmelshavere = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HjemmelshavereSpecified
        {
            get
            {
                return (this.Hjemmelshavere.Count != 0);
            }
        }
        
        public Boligdetaljer()
        {
            this._hjemmelshavere = new System.Collections.ObjectModel.Collection<Hjemmelshaver>();
            this._omsetningshistorikk = new System.Collections.ObjectModel.Collection<Omsetningshistorikk>();
            this._heftelser = new System.Collections.ObjectModel.Collection<Heftelse>();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("bruksareal", Namespace="http://api.digipost.no/schema/datatypes")]
        public int BruksarealValue { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool BruksarealValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<int> Bruksareal
        {
            get
            {
                if (this.BruksarealValueSpecified)
                {
                    return this.BruksarealValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.BruksarealValue = value.GetValueOrDefault();
                this.BruksarealValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("antall-oppholdsrom", Namespace="http://api.digipost.no/schema/datatypes")]
        public int Antall_OppholdsromValue { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool Antall_OppholdsromValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<int> Antall_Oppholdsrom
        {
            get
            {
                if (this.Antall_OppholdsromValueSpecified)
                {
                    return this.Antall_OppholdsromValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.Antall_OppholdsromValue = value.GetValueOrDefault();
                this.Antall_OppholdsromValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("antall-baderom", Namespace="http://api.digipost.no/schema/datatypes")]
        public int Antall_BaderomValue { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool Antall_BaderomValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<int> Antall_Baderom
        {
            get
            {
                if (this.Antall_BaderomValueSpecified)
                {
                    return this.Antall_BaderomValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.Antall_BaderomValue = value.GetValueOrDefault();
                this.Antall_BaderomValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Omsetningshistorikk> _omsetningshistorikk;
        
        [System.Xml.Serialization.XmlElementAttribute("omsetningshistorikk", Namespace="http://api.digipost.no/schema/datatypes")]
        public System.Collections.ObjectModel.Collection<Omsetningshistorikk> Omsetningshistorikk
        {
            get
            {
                return this._omsetningshistorikk;
            }
            private set
            {
                this._omsetningshistorikk = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OmsetningshistorikkSpecified
        {
            get
            {
                return (this.Omsetningshistorikk.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("organisasjonsnummer", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Organisasjonsnummer { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("bruksenhet", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Bruksenhet { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("andelsnummer", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Andelsnummer { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Heftelse> _heftelser;
        
        [System.Xml.Serialization.XmlElementAttribute("heftelser", Namespace="http://api.digipost.no/schema/datatypes")]
        public System.Collections.ObjectModel.Collection<Heftelse> Heftelser
        {
            get
            {
                return this._heftelser;
            }
            private set
            {
                this._heftelser = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HeftelserSpecified
        {
            get
            {
                return (this.Heftelser.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("callToAction", Namespace="http://api.digipost.no/schema/datatypes")]
        public ExternalLink CallToAction { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("residence", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("residence", Namespace="http://api.digipost.no/schema/datatypes")]
    public partial class Residence
    {
        
        [System.Xml.Serialization.XmlElementAttribute("address", Namespace="http://api.digipost.no/schema/datatypes")]
        public ResidenceAddress Address { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("matrikkel", Namespace="http://api.digipost.no/schema/datatypes")]
        public Matrikkel Matrikkel { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("source", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Source { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("external-id", Namespace="http://api.digipost.no/schema/datatypes")]
        public string External_Id { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("residenceAddress", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ResidenceAddress
    {
        
        [System.Xml.Serialization.XmlElementAttribute("unit-number", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Unit_Number { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("house-number", Namespace="http://api.digipost.no/schema/datatypes")]
        public string House_Number { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("street-name", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Street_Name { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("postal-code", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Postal_Code { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("city", Namespace="http://api.digipost.no/schema/datatypes")]
        public string City { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("matrikkel", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Matrikkel
    {
        
        [System.Xml.Serialization.XmlElementAttribute("kommunenummer", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Kommunenummer { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("gaardsnummer", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Gaardsnummer { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("bruksnummer", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Bruksnummer { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("festenummer", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Festenummer { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("seksjonsnummer", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Seksjonsnummer { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("hjemmelshaver", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Hjemmelshaver
    {
        
        [System.Xml.Serialization.XmlElementAttribute("name", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Name { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("email", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Email { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("omsetningshistorikk", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Omsetningshistorikk
    {
        
        [System.Xml.Serialization.XmlElementAttribute("dato", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Dato { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("beskrivelse", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Beskrivelse { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("selger", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Selger { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("kjoeper", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Kjoeper { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("beloep", Namespace="http://api.digipost.no/schema/datatypes")]
        public long BeloepValue { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool BeloepValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<long> Beloep
        {
            get
            {
                if (this.BeloepValueSpecified)
                {
                    return this.BeloepValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.BeloepValue = value.GetValueOrDefault();
                this.BeloepValueSpecified = value.HasValue;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("heftelse", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Heftelse
    {
        
        [System.Xml.Serialization.XmlElementAttribute("panthaver", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Panthaver { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("type-pant", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Type_Pant { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("beloep", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Beloep { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("externalLink", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("externalLink", Namespace="http://api.digipost.no/schema/datatypes")]
    public partial class ExternalLink
    {
        
        [System.Xml.Serialization.XmlElementAttribute("url", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Url { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("deadline", Namespace="http://api.digipost.no/schema/datatypes", DataType="dateTime")]
        public System.DateTime DeadlineValue { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool DeadlineValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> Deadline
        {
            get
            {
                if (this.DeadlineValueSpecified)
                {
                    return this.DeadlineValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.DeadlineValue = value.GetValueOrDefault();
                this.DeadlineValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("description", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Description { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("button-text", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Button_Text { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("event", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("event", Namespace="http://api.digipost.no/schema/datatypes")]
    public partial class Event
    {
        
        [System.Xml.Serialization.XmlElementAttribute("sub-title", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Sub_Title { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<TimeInterval> _start_Time;
        
        [System.Xml.Serialization.XmlElementAttribute("start-time", Namespace="http://api.digipost.no/schema/datatypes")]
        public System.Collections.ObjectModel.Collection<TimeInterval> Start_Time
        {
            get
            {
                return this._start_Time;
            }
            private set
            {
                this._start_Time = value;
            }
        }
        
        public Event()
        {
            this._start_Time = new System.Collections.ObjectModel.Collection<TimeInterval>();
            this._info = new System.Collections.ObjectModel.Collection<Info>();
            this._links = new System.Collections.ObjectModel.Collection<Link>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("timeLabel", Namespace="http://api.digipost.no/schema/datatypes")]
        public string TimeLabel { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("description", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Description { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("place", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Place { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("placeLabel", Namespace="http://api.digipost.no/schema/datatypes")]
        public string PlaceLabel { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("address", Namespace="http://api.digipost.no/schema/datatypes")]
        public Address Address { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Info> _info;
        
        [System.Xml.Serialization.XmlElementAttribute("info", Namespace="http://api.digipost.no/schema/datatypes")]
        public System.Collections.ObjectModel.Collection<Info> Info
        {
            get
            {
                return this._info;
            }
            private set
            {
                this._info = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InfoSpecified
        {
            get
            {
                return (this.Info.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("barcodeLabel", Namespace="http://api.digipost.no/schema/datatypes")]
        public string BarcodeLabel { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("barcode", Namespace="http://api.digipost.no/schema/datatypes")]
        public Barcode Barcode { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Link> _links;
        
        [System.Xml.Serialization.XmlElementAttribute("links", Namespace="http://api.digipost.no/schema/datatypes")]
        public System.Collections.ObjectModel.Collection<Link> Links
        {
            get
            {
                return this._links;
            }
            private set
            {
                this._links = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LinksSpecified
        {
            get
            {
                return (this.Links.Count != 0);
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("timeInterval", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TimeInterval
    {
        
        [System.Xml.Serialization.XmlElementAttribute("start-time", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Start_Time { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("end-time", Namespace="http://api.digipost.no/schema/datatypes")]
        public string End_Time { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("link", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Link
    {
        
        [System.Xml.Serialization.XmlElementAttribute("url", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Url { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("description", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Description { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("foreignCurrencyPayment", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ForeignCurrencyPayment
    {
        
        [System.Xml.Serialization.XmlElementAttribute("currency-code", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Currency_Code { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("amount", Namespace="http://api.digipost.no/schema/datatypes")]
        public decimal AmountValue { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool AmountValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<decimal> Amount
        {
            get
            {
                if (this.AmountValueSpecified)
                {
                    return this.AmountValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.AmountValue = value.GetValueOrDefault();
                this.AmountValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("exchange-rate", Namespace="http://api.digipost.no/schema/datatypes")]
        public decimal Exchange_RateValue { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool Exchange_RateValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<decimal> Exchange_Rate
        {
            get
            {
                if (this.Exchange_RateValueSpecified)
                {
                    return this.Exchange_RateValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.Exchange_RateValue = value.GetValueOrDefault();
                this.Exchange_RateValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("label", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Label { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("payslip", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("payslip", Namespace="http://api.digipost.no/schema/datatypes")]
    public partial class Payslip
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("signedDocument", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("signedDocument", Namespace="http://api.digipost.no/schema/datatypes")]
    public partial class SignedDocument
    {
        
        [System.Xml.Serialization.XmlElementAttribute("document-issuer", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Document_Issuer { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("document-subject", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Document_Subject { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("signing-time", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Signing_Time { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("cost", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Cost
    {
        
        [System.Xml.Serialization.XmlElementAttribute("value-to-be-payed", Namespace="http://api.digipost.no/schema/datatypes")]
        public decimal Value_To_Be_Payed { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("package-value", Namespace="http://api.digipost.no/schema/datatypes")]
        public decimal Package_ValueValue { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool Package_ValueValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<decimal> Package_Value
        {
            get
            {
                if (this.Package_ValueValueSpecified)
                {
                    return this.Package_ValueValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.Package_ValueValue = value.GetValueOrDefault();
                this.Package_ValueValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("customs-fee-outlayed", Namespace="http://api.digipost.no/schema/datatypes")]
        public decimal Customs_Fee_OutlayedValue { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool Customs_Fee_OutlayedValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<decimal> Customs_Fee_Outlayed
        {
            get
            {
                if (this.Customs_Fee_OutlayedValueSpecified)
                {
                    return this.Customs_Fee_OutlayedValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.Customs_Fee_OutlayedValue = value.GetValueOrDefault();
                this.Customs_Fee_OutlayedValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("vas-text", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Vas_Text { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("customs-fee", Namespace="http://api.digipost.no/schema/datatypes")]
        public decimal Customs_FeeValue { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool Customs_FeeValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<decimal> Customs_Fee
        {
            get
            {
                if (this.Customs_FeeValueSpecified)
                {
                    return this.Customs_FeeValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.Customs_FeeValue = value.GetValueOrDefault();
                this.Customs_FeeValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("customs-fee-outlay-cost", Namespace="http://api.digipost.no/schema/datatypes")]
        public decimal Customs_Fee_Outlay_CostValue { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool Customs_Fee_Outlay_CostValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<decimal> Customs_Fee_Outlay_Cost
        {
            get
            {
                if (this.Customs_Fee_Outlay_CostValueSpecified)
                {
                    return this.Customs_Fee_Outlay_CostValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.Customs_Fee_Outlay_CostValue = value.GetValueOrDefault();
                this.Customs_Fee_Outlay_CostValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("cod-amount", Namespace="http://api.digipost.no/schema/datatypes")]
        public decimal Cod_AmountValue { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool Cod_AmountValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<decimal> Cod_Amount
        {
            get
            {
                if (this.Cod_AmountValueSpecified)
                {
                    return this.Cod_AmountValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.Cod_AmountValue = value.GetValueOrDefault();
                this.Cod_AmountValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("cod-fee", Namespace="http://api.digipost.no/schema/datatypes")]
        public decimal Cod_FeeValue { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool Cod_FeeValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<decimal> Cod_Fee
        {
            get
            {
                if (this.Cod_FeeValueSpecified)
                {
                    return this.Cod_FeeValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.Cod_FeeValue = value.GetValueOrDefault();
                this.Cod_FeeValueSpecified = value.HasValue;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("package", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Package
    {
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("length", Namespace="http://api.digipost.no/schema/datatypes")]
        public int LengthValue { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool LengthValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<int> Length
        {
            get
            {
                if (this.LengthValueSpecified)
                {
                    return this.LengthValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.LengthValue = value.GetValueOrDefault();
                this.LengthValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("width", Namespace="http://api.digipost.no/schema/datatypes")]
        public int WidthValue { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool WidthValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<int> Width
        {
            get
            {
                if (this.WidthValueSpecified)
                {
                    return this.WidthValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.WidthValue = value.GetValueOrDefault();
                this.WidthValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("height", Namespace="http://api.digipost.no/schema/datatypes")]
        public int HeightValue { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool HeightValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<int> Height
        {
            get
            {
                if (this.HeightValueSpecified)
                {
                    return this.HeightValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.HeightValue = value.GetValueOrDefault();
                this.HeightValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("weight", Namespace="http://api.digipost.no/schema/datatypes")]
        public int WeightValue { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool WeightValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<int> Weight
        {
            get
            {
                if (this.WeightValueSpecified)
                {
                    return this.WeightValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.WeightValue = value.GetValueOrDefault();
                this.WeightValueSpecified = value.HasValue;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("pickupNotice", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("pickup-notice", Namespace="http://api.digipost.no/schema/datatypes")]
    public partial class PickupNotice
    {
        
        [System.Xml.Serialization.XmlElementAttribute("parcel-id", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Parcel_Id { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("parcel-uuid", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Parcel_Uuid { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("barcode", Namespace="http://api.digipost.no/schema/datatypes")]
        public Barcode Barcode { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("product-name", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Product_Name { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("arrival-date-time", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Arrival_Date_Time { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("return-date-time", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Return_Date_Time { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("recipient", Namespace="http://api.digipost.no/schema/datatypes")]
        public Recipient Recipient { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("sender", Namespace="http://api.digipost.no/schema/datatypes")]
        public Sender Sender { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("pickup-place", Namespace="http://api.digipost.no/schema/datatypes")]
        public PickupPlace Pickup_Place { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("package", Namespace="http://api.digipost.no/schema/datatypes")]
        public Package Package { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("cost", Namespace="http://api.digipost.no/schema/datatypes")]
        public Cost Cost { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("status", Namespace="http://api.digipost.no/schema/datatypes")]
        public Status StatusValue { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool StatusValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<Status> Status
        {
            get
            {
                if (this.StatusValueSpecified)
                {
                    return this.StatusValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.StatusValue = value.GetValueOrDefault();
                this.StatusValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Tag> _tags;
        
        [System.Xml.Serialization.XmlElementAttribute("tags", Namespace="http://api.digipost.no/schema/datatypes")]
        public System.Collections.ObjectModel.Collection<Tag> Tags
        {
            get
            {
                return this._tags;
            }
            private set
            {
                this._tags = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TagsSpecified
        {
            get
            {
                return (this.Tags.Count != 0);
            }
        }
        
        public PickupNotice()
        {
            this._tags = new System.Collections.ObjectModel.Collection<Tag>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("recipient", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Recipient
    {
        
        [System.Xml.Serialization.XmlElementAttribute("name", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Name { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("digipost-address", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Digipost_Address { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("address", Namespace="http://api.digipost.no/schema/datatypes")]
        public Address Address { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("sender", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Sender
    {
        
        [System.Xml.Serialization.XmlElementAttribute("name", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Name { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("reference", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Reference { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("address", Namespace="http://api.digipost.no/schema/datatypes")]
        public Address Address { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("pickupPlace", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PickupPlace
    {
        
        [System.Xml.Serialization.XmlElementAttribute("name", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Name { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("code", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Code { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("instruction", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Instruction { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("shelf-location", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Shelf_Location { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("address", Namespace="http://api.digipost.no/schema/datatypes")]
        public Address Address { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("status", Namespace="http://api.digipost.no/schema/datatypes")]
    public enum Status
    {
        
        READY_FOR_PICKUP,
        
        DEVIATION,
        
        RETURNED,
        
        PICKED_UP,
        
        UNKNOWN,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("tag", Namespace="http://api.digipost.no/schema/datatypes")]
    public enum Tag
    {
        
        VARSEL2,
        
        POSTEN,
        
        VARSEL1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("pickupNoticeStatus", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("pickup-notice-status", Namespace="http://api.digipost.no/schema/datatypes")]
    public partial class PickupNoticeStatus
    {
        
        [System.Xml.Serialization.XmlElementAttribute("status", Namespace="http://api.digipost.no/schema/datatypes")]
        public Status Status { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("occurrence-datetime", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Occurrence_Datetime { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("calendarDate", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CalendarDate
    {
        
        [System.Xml.Serialization.XmlElementAttribute("month", Namespace="http://api.digipost.no/schema/datatypes")]
        public int Month { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("day", Namespace="http://api.digipost.no/schema/datatypes")]
        public int Day { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private int _hour = 0;
        
        [System.ComponentModel.DefaultValueAttribute(0)]
        [System.Xml.Serialization.XmlElementAttribute("hour", Namespace="http://api.digipost.no/schema/datatypes")]
        public int Hour
        {
            get
            {
                return this._hour;
            }
            set
            {
                this._hour = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private int _min = 0;
        
        [System.ComponentModel.DefaultValueAttribute(0)]
        [System.Xml.Serialization.XmlElementAttribute("min", Namespace="http://api.digipost.no/schema/datatypes")]
        public int Min
        {
            get
            {
                return this._min;
            }
            set
            {
                this._min = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _time_Zone = "+01:00";
        
        [System.ComponentModel.DefaultValueAttribute("+01:00")]
        [System.Xml.Serialization.XmlElementAttribute("time-zone", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Time_Zone
        {
            get
            {
                return this._time_Zone;
            }
            set
            {
                this._time_Zone = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("period", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Period
    {
        
        [System.Xml.Serialization.XmlElementAttribute("from", Namespace="http://api.digipost.no/schema/datatypes")]
        public string From { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("to", Namespace="http://api.digipost.no/schema/datatypes")]
        public string To { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("proof", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("proof", Namespace="http://api.digipost.no/schema/datatypes")]
    public partial class Proof
    {
        
        [System.Xml.Serialization.XmlElementAttribute("authorizer-name", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Authorizer_Name { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("background-color", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Background_Color { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("issued-time", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Issued_Time { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("valid-period", Namespace="http://api.digipost.no/schema/datatypes")]
        public ValidPeriod Valid_Period { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("proof-holder", Namespace="http://api.digipost.no/schema/datatypes")]
        public ProofHolder Proof_Holder { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("title", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Title { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("proof-id-name", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Proof_Id_Name { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("proof-id-value", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Proof_Id_Value { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Info> _attribute;
        
        [System.Xml.Serialization.XmlElementAttribute("attribute", Namespace="http://api.digipost.no/schema/datatypes")]
        public System.Collections.ObjectModel.Collection<Info> Attribute
        {
            get
            {
                return this._attribute;
            }
            private set
            {
                this._attribute = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AttributeSpecified
        {
            get
            {
                return (this.Attribute.Count != 0);
            }
        }
        
        public Proof()
        {
            this._attribute = new System.Collections.ObjectModel.Collection<Info>();
            this._info = new System.Collections.ObjectModel.Collection<Info>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Info> _info;
        
        [System.Xml.Serialization.XmlElementAttribute("info", Namespace="http://api.digipost.no/schema/datatypes")]
        public System.Collections.ObjectModel.Collection<Info> Info
        {
            get
            {
                return this._info;
            }
            private set
            {
                this._info = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InfoSpecified
        {
            get
            {
                return (this.Info.Count != 0);
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("validPeriod", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidPeriod
    {
        
        [System.Xml.Serialization.XmlElementAttribute("period", Namespace="http://api.digipost.no/schema/datatypes")]
        public Period Period { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("yearly-repeating-period", Namespace="http://api.digipost.no/schema/datatypes")]
        public YearlyRepeatingPeriod Yearly_Repeating_Period { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("yearlyRepeatingPeriod", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class YearlyRepeatingPeriod
    {
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("start-year", Namespace="http://api.digipost.no/schema/datatypes")]
        public int Start_YearValue { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool Start_YearValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<int> Start_Year
        {
            get
            {
                if (this.Start_YearValueSpecified)
                {
                    return this.Start_YearValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.Start_YearValue = value.GetValueOrDefault();
                this.Start_YearValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("end-year", Namespace="http://api.digipost.no/schema/datatypes")]
        public int End_YearValue { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool End_YearValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<int> End_Year
        {
            get
            {
                if (this.End_YearValueSpecified)
                {
                    return this.End_YearValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.End_YearValue = value.GetValueOrDefault();
                this.End_YearValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("from", Namespace="http://api.digipost.no/schema/datatypes")]
        public CalendarDate From { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("to", Namespace="http://api.digipost.no/schema/datatypes")]
        public CalendarDate To { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("proofHolder", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProofHolder
    {
        
        [System.Xml.Serialization.XmlElementAttribute("firstname", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Firstname { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("surname", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Surname { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("social-security-number", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Social_Security_Number { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("address", Namespace="http://api.digipost.no/schema/datatypes")]
        public Address Address { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("customer", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Customer
    {
        
        [System.Xml.Serialization.XmlElementAttribute("name", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Name { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("address", Namespace="http://api.digipost.no/schema/datatypes")]
        public Address Address { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("phoneNumber", Namespace="http://api.digipost.no/schema/datatypes")]
        public string PhoneNumber { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("delivery", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Delivery
    {
        
        [System.Xml.Serialization.XmlElementAttribute("name", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Name { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("address", Namespace="http://api.digipost.no/schema/datatypes")]
        public Address Address { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("terms", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Terms { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("payment", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Payment
    {
        
        [System.Xml.Serialization.XmlElementAttribute("type", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Type { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("card-number", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Card_Number { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("cardName", Namespace="http://api.digipost.no/schema/datatypes")]
        public string CardName { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("amount", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Amount { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("currency-code", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Currency_Code { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("foreign-currency-payment", Namespace="http://api.digipost.no/schema/datatypes")]
        public ForeignCurrencyPayment Foreign_Currency_Payment { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("receipt", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("receipt", Namespace="http://api.digipost.no/schema/datatypes")]
    public partial class Receipt
    {
        
        [System.Xml.Serialization.XmlElementAttribute("receiptId", Namespace="http://api.digipost.no/schema/datatypes")]
        public string ReceiptId { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("receiptNumber", Namespace="http://api.digipost.no/schema/datatypes")]
        public string ReceiptNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("purchaseTime", Namespace="http://api.digipost.no/schema/datatypes")]
        public string PurchaseTime { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("totalPrice", Namespace="http://api.digipost.no/schema/datatypes")]
        public string TotalPrice { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("totalVat", Namespace="http://api.digipost.no/schema/datatypes")]
        public string TotalVat { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("currency", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Currency { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("cashier", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Cashier { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("register", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Register { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("merchant-chain", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Merchant_Chain { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("merchant-name", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Merchant_Name { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("merchant-phone-number", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Merchant_Phone_Number { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("merchant-address", Namespace="http://api.digipost.no/schema/datatypes")]
        public Address Merchant_Address { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("orgnumber", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Orgnumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("barcode", Namespace="http://api.digipost.no/schema/datatypes")]
        public Barcode Barcode { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Payment> _payments;
        
        [System.Xml.Serialization.XmlElementAttribute("payments", Namespace="http://api.digipost.no/schema/datatypes")]
        public System.Collections.ObjectModel.Collection<Payment> Payments
        {
            get
            {
                return this._payments;
            }
            private set
            {
                this._payments = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PaymentsSpecified
        {
            get
            {
                return (this.Payments.Count != 0);
            }
        }
        
        public Receipt()
        {
            this._payments = new System.Collections.ObjectModel.Collection<Payment>();
            this._items = new System.Collections.ObjectModel.Collection<ReceiptLine>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ReceiptLine> _items;
        
        [System.Xml.Serialization.XmlElementAttribute("items", Namespace="http://api.digipost.no/schema/datatypes")]
        public System.Collections.ObjectModel.Collection<ReceiptLine> Items
        {
            get
            {
                return this._items;
            }
            private set
            {
                this._items = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ItemsSpecified
        {
            get
            {
                return (this.Items.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("taxiDetails", Namespace="http://api.digipost.no/schema/datatypes")]
        public TaxiDetails TaxiDetails { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("customer", Namespace="http://api.digipost.no/schema/datatypes")]
        public Customer Customer { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("delivery", Namespace="http://api.digipost.no/schema/datatypes")]
        public Delivery Delivery { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("order-number", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Order_Number { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("membership-number", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Membership_Number { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("comment", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Comment { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("receiptLine", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReceiptLine
    {
        
        [System.Xml.Serialization.XmlElementAttribute("item-name", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Item_Name { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("item-description", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Item_Description { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("item-code", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Item_Code { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("unit", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Unit { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("quantity", Namespace="http://api.digipost.no/schema/datatypes")]
        public double Quantity { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("item-price", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Item_Price { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("item-vat", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Item_Vat { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("total-price", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Total_Price { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("total-vat", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Total_Vat { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("discount", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Discount { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("serialNumber", Namespace="http://api.digipost.no/schema/datatypes")]
        public string SerialNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("eanCode", Namespace="http://api.digipost.no/schema/datatypes")]
        public string EanCode { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("taxiDetails", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TaxiDetails
    {
        
        [System.Xml.Serialization.XmlElementAttribute("carPlateNumber", Namespace="http://api.digipost.no/schema/datatypes")]
        public string CarPlateNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("license", Namespace="http://api.digipost.no/schema/datatypes")]
        public string License { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("orgNumberLicenseHolder", Namespace="http://api.digipost.no/schema/datatypes")]
        public string OrgNumberLicenseHolder { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("startTime", Namespace="http://api.digipost.no/schema/datatypes")]
        public string StartTime { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("stopTime", Namespace="http://api.digipost.no/schema/datatypes")]
        public string StopTime { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("tips", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Tips { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("totalMeterPrice", Namespace="http://api.digipost.no/schema/datatypes")]
        public string TotalMeterPrice { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("totalDistanceBeforeBoardingInMeters", Namespace="http://api.digipost.no/schema/datatypes")]
        public int TotalDistanceBeforeBoardingInMetersValue { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool TotalDistanceBeforeBoardingInMetersValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<int> TotalDistanceBeforeBoardingInMeters
        {
            get
            {
                if (this.TotalDistanceBeforeBoardingInMetersValueSpecified)
                {
                    return this.TotalDistanceBeforeBoardingInMetersValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.TotalDistanceBeforeBoardingInMetersValue = value.GetValueOrDefault();
                this.TotalDistanceBeforeBoardingInMetersValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("totalDistanceInMeters", Namespace="http://api.digipost.no/schema/datatypes")]
        public int TotalDistanceInMetersValue { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool TotalDistanceInMetersValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<int> TotalDistanceInMeters
        {
            get
            {
                if (this.TotalDistanceInMetersValueSpecified)
                {
                    return this.TotalDistanceInMetersValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.TotalDistanceInMetersValue = value.GetValueOrDefault();
                this.TotalDistanceInMetersValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("totalDistanceWithPassengerInMeters", Namespace="http://api.digipost.no/schema/datatypes")]
        public int TotalDistanceWithPassengerInMetersValue { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool TotalDistanceWithPassengerInMetersValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<int> TotalDistanceWithPassengerInMeters
        {
            get
            {
                if (this.TotalDistanceWithPassengerInMetersValueSpecified)
                {
                    return this.TotalDistanceWithPassengerInMetersValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.TotalDistanceWithPassengerInMetersValue = value.GetValueOrDefault();
                this.TotalDistanceWithPassengerInMetersValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("totalTimeBeforeBoardingInSeconds", Namespace="http://api.digipost.no/schema/datatypes")]
        public int TotalTimeBeforeBoardingInSecondsValue { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool TotalTimeBeforeBoardingInSecondsValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<int> TotalTimeBeforeBoardingInSeconds
        {
            get
            {
                if (this.TotalTimeBeforeBoardingInSecondsValueSpecified)
                {
                    return this.TotalTimeBeforeBoardingInSecondsValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.TotalTimeBeforeBoardingInSecondsValue = value.GetValueOrDefault();
                this.TotalTimeBeforeBoardingInSecondsValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("totalTimeInSeconds", Namespace="http://api.digipost.no/schema/datatypes")]
        public int TotalTimeInSecondsValue { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool TotalTimeInSecondsValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<int> TotalTimeInSeconds
        {
            get
            {
                if (this.TotalTimeInSecondsValueSpecified)
                {
                    return this.TotalTimeInSecondsValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.TotalTimeInSecondsValue = value.GetValueOrDefault();
                this.TotalTimeInSecondsValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("totalTimeWithPassengerInSeconds", Namespace="http://api.digipost.no/schema/datatypes")]
        public int TotalTimeWithPassengerInSecondsValue { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool TotalTimeWithPassengerInSecondsValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<int> TotalTimeWithPassengerInSeconds
        {
            get
            {
                if (this.TotalTimeWithPassengerInSecondsValueSpecified)
                {
                    return this.TotalTimeWithPassengerInSecondsValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.TotalTimeWithPassengerInSecondsValue = value.GetValueOrDefault();
                this.TotalTimeWithPassengerInSecondsValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("vat", Namespace="http://api.digipost.no/schema/datatypes")]
        public VatDetails Vat { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("vatDetails", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VatDetails
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<VatLevel> _levels;
        
        [System.Xml.Serialization.XmlElementAttribute("levels", Namespace="http://api.digipost.no/schema/datatypes")]
        public System.Collections.ObjectModel.Collection<VatLevel> Levels
        {
            get
            {
                return this._levels;
            }
            private set
            {
                this._levels = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LevelsSpecified
        {
            get
            {
                return (this.Levels.Count != 0);
            }
        }
        
        public VatDetails()
        {
            this._levels = new System.Collections.ObjectModel.Collection<VatLevel>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("sum", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Sum { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("vatLevel", Namespace="http://api.digipost.no/schema/datatypes")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VatLevel
    {
        
        [System.Xml.Serialization.XmlElementAttribute("grossAmount", Namespace="http://api.digipost.no/schema/datatypes")]
        public string GrossAmount { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("netAmount", Namespace="http://api.digipost.no/schema/datatypes")]
        public string NetAmount { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("vat", Namespace="http://api.digipost.no/schema/datatypes")]
        public string Vat { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("vatPercent", Namespace="http://api.digipost.no/schema/datatypes")]
        public string VatPercent { get; set; }
    }
}
