//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//This source code was auto-generated by MonoXSD
//
namespace Api_v7 {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.digipost.no/schema/v7")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://api.digipost.no/schema/v7", IsNullable=false)]
    public partial class entrypoint {
        
        private string certificateField;
        
        private link[] linkField;
        
        /// <remarks/>
        public string certificate {
            get {
                return this.certificateField;
            }
            set {
                this.certificateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("link")]
        public link[] link {
            get {
                return this.linkField;
            }
            set {
                this.linkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.digipost.no/schema/v7")]
    public partial class link {
        
        private string relField;
        
        private string uriField;
        
        private string mediatypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string rel {
            get {
                return this.relField;
            }
            set {
                this.relField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string uri {
            get {
                return this.uriField;
            }
            set {
                this.uriField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("media-type")]
        public string mediatype {
            get {
                return this.mediatypeField;
            }
            set {
                this.mediatypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="inbox-document", Namespace="http://api.digipost.no/schema/v7")]
    public partial class inboxdocument {
        
        private long idField;
        
        private string referencefromsenderField;
        
        private string subjectField;
        
        private string senderField;
        
        private System.DateTime deliverytimeField;
        
        private System.DateTime firstaccessedField;
        
        private bool firstaccessedFieldSpecified;
        
        private authenticationlevel authenticationlevelField;
        
        private string contenttypeField;
        
        private string contenturiField;
        
        private string deleteuriField;
        
        private inboxdocument[] attachmentField;
        
        /// <remarks/>
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("reference-from-sender")]
        public string referencefromsender {
            get {
                return this.referencefromsenderField;
            }
            set {
                this.referencefromsenderField = value;
            }
        }
        
        /// <remarks/>
        public string subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
            }
        }
        
        /// <remarks/>
        public string sender {
            get {
                return this.senderField;
            }
            set {
                this.senderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("delivery-time")]
        public System.DateTime deliverytime {
            get {
                return this.deliverytimeField;
            }
            set {
                this.deliverytimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("first-accessed")]
        public System.DateTime firstaccessed {
            get {
                return this.firstaccessedField;
            }
            set {
                this.firstaccessedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool firstaccessedSpecified {
            get {
                return this.firstaccessedFieldSpecified;
            }
            set {
                this.firstaccessedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("authentication-level")]
        public authenticationlevel authenticationlevel {
            get {
                return this.authenticationlevelField;
            }
            set {
                this.authenticationlevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("content-type")]
        public string contenttype {
            get {
                return this.contenttypeField;
            }
            set {
                this.contenttypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("content-uri")]
        public string contenturi {
            get {
                return this.contenturiField;
            }
            set {
                this.contenturiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("delete-uri")]
        public string deleteuri {
            get {
                return this.deleteuriField;
            }
            set {
                this.deleteuriField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("attachment")]
        public inboxdocument[] attachment {
            get {
                return this.attachmentField;
            }
            set {
                this.attachmentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="authentication-level", Namespace="http://api.digipost.no/schema/v7")]
    public enum authenticationlevel {
        
        /// <remarks/>
        PASSWORD,
        
        /// <remarks/>
        TWO_FACTOR,
        
        /// <remarks/>
        IDPORTEN_3,
        
        /// <remarks/>
        IDPORTEN_4,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="document-metadata", Namespace="http://api.digipost.no/schema/v7")]
    public partial class documentmetadata {
        
        private link[] linkField;
        
        private string uuidField;
        
        private string technicaltypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("link")]
        public link[] link {
            get {
                return this.linkField;
            }
            set {
                this.linkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("technical-type")]
        public string technicaltype {
            get {
                return this.technicaltypeField;
            }
            set {
                this.technicaltypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(postmarkedmetadata))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(failedprintmetadata))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(smsnotificationfailedmetadata))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(emailnotificationfailedmetadata))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(movefilesfrompublicsectormetadata))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="event-metadata", Namespace="http://api.digipost.no/schema/v7")]
    public abstract partial class eventmetadata {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="postmarked-metadata", Namespace="http://api.digipost.no/schema/v7")]
    public partial class postmarkedmetadata : eventmetadata {
        
        private System.DateTime postmarkeddateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("postmarked-date")]
        public System.DateTime postmarkeddate {
            get {
                return this.postmarkeddateField;
            }
            set {
                this.postmarkeddateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="failed-print-metadata", Namespace="http://api.digipost.no/schema/v7")]
    public partial class failedprintmetadata : eventmetadata {
        
        private string errorcodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("error-code")]
        public string errorcode {
            get {
                return this.errorcodeField;
            }
            set {
                this.errorcodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="sms-notification-failed-metadata", Namespace="http://api.digipost.no/schema/v7")]
    public partial class smsnotificationfailedmetadata : eventmetadata {
        
        private string mobilenumberField;
        
        private string errorcodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("mobile-number")]
        public string mobilenumber {
            get {
                return this.mobilenumberField;
            }
            set {
                this.mobilenumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("error-code")]
        public string errorcode {
            get {
                return this.errorcodeField;
            }
            set {
                this.errorcodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="email-notification-failed-metadata", Namespace="http://api.digipost.no/schema/v7")]
    public partial class emailnotificationfailedmetadata : eventmetadata {
        
        private string emailaddressField;
        
        private string errorcodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("email-address")]
        public string emailaddress {
            get {
                return this.emailaddressField;
            }
            set {
                this.emailaddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("error-code")]
        public string errorcode {
            get {
                return this.errorcodeField;
            }
            set {
                this.errorcodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="move-files-from-public-sector-metadata", Namespace="http://api.digipost.no/schema/v7")]
    public partial class movefilesfrompublicsectormetadata : eventmetadata {
        
        private documentmetadata[] documentField;
        
        private string x509CertificateField;
        
        private bool openedField;
        
        private System.DateTime deliverytimeField;
        
        private string subjectField;
        
        private authenticationlevel authenticationlevelField;
        
        private sensitivitylevel sensitivitylevelField;
        
        private string destinationmailboxField;
        
        private string destinationmailboxaddressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("document")]
        public documentmetadata[] document {
            get {
                return this.documentField;
            }
            set {
                this.documentField = value;
            }
        }
        
        /// <remarks/>
        public string x509Certificate {
            get {
                return this.x509CertificateField;
            }
            set {
                this.x509CertificateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool opened {
            get {
                return this.openedField;
            }
            set {
                this.openedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("delivery-time")]
        public System.DateTime deliverytime {
            get {
                return this.deliverytimeField;
            }
            set {
                this.deliverytimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("authentication-level")]
        public authenticationlevel authenticationlevel {
            get {
                return this.authenticationlevelField;
            }
            set {
                this.authenticationlevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("sensitivity-level")]
        public sensitivitylevel sensitivitylevel {
            get {
                return this.sensitivitylevelField;
            }
            set {
                this.sensitivitylevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("destination-mailbox")]
        public string destinationmailbox {
            get {
                return this.destinationmailboxField;
            }
            set {
                this.destinationmailboxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("destination-mailbox-address")]
        public string destinationmailboxaddress {
            get {
                return this.destinationmailboxaddressField;
            }
            set {
                this.destinationmailboxaddressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="sensitivity-level", Namespace="http://api.digipost.no/schema/v7")]
    public enum sensitivitylevel {
        
        /// <remarks/>
        NORMAL,
        
        /// <remarks/>
        SENSITIVE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.digipost.no/schema/v7")]
    public partial class @event {
        
        private eventmetadata metadataField;
        
        private string uuidField;
        
        private eventtype typeField;
        
        private System.DateTime createdField;
        
        private System.DateTime documentcreatedField;
        
        /// <remarks/>
        public eventmetadata metadata {
            get {
                return this.metadataField;
            }
            set {
                this.metadataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public eventtype type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("document-created")]
        public System.DateTime documentcreated {
            get {
                return this.documentcreatedField;
            }
            set {
                this.documentcreatedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="event-type", Namespace="http://api.digipost.no/schema/v7")]
    public enum eventtype {
        
        /// <remarks/>
        EMAIL_NOTIFICATION_FAILED,
        
        /// <remarks/>
        SMS_NOTIFICATION_FAILED,
        
        /// <remarks/>
        OPENED,
        
        /// <remarks/>
        MOVE_FILES_FROM_PUBLIC_SECTOR,
        
        /// <remarks/>
        POSTMARKED,
        
        /// <remarks/>
        PRINT_FAILED,
        
        /// <remarks/>
        SHREDDED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.digipost.no/schema/v7")]
    public partial class feature {
        
        private string paramField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string param {
            get {
                return this.paramField;
            }
            set {
                this.paramField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="sender-organization", Namespace="http://api.digipost.no/schema/v7")]
    public partial class senderorganization {
        
        private string organizationidField;
        
        private string partidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("organization-id")]
        public string organizationid {
            get {
                return this.organizationidField;
            }
            set {
                this.organizationidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("part-id")]
        public string partid {
            get {
                return this.partidField;
            }
            set {
                this.partidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="content-hash", Namespace="http://api.digipost.no/schema/v7")]
    public partial class contenthash {
        
        private string hashalgorithmField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("hash-algorithm")]
        public string hashalgorithm {
            get {
                return this.hashalgorithmField;
            }
            set {
                this.hashalgorithmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.digipost.no/schema/v7")]
    public partial class encrypted {
        
        private int numberofpagesField;
        
        private bool numberofpagesFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("number-of-pages")]
        public int numberofpages {
            get {
                return this.numberofpagesField;
            }
            set {
                this.numberofpagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numberofpagesSpecified {
            get {
                return this.numberofpagesFieldSpecified;
            }
            set {
                this.numberofpagesFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="email-notification", Namespace="http://api.digipost.no/schema/v7")]
    public partial class emailnotification {
        
        private string emailaddressField;
        
        private string subjectField;
        
        private string textField;
        
        private listedtime[] atField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("email-address")]
        public string emailaddress {
            get {
                return this.emailaddressField;
            }
            set {
                this.emailaddressField = value;
            }
        }
        
        /// <remarks/>
        public string subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
            }
        }
        
        /// <remarks/>
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("at")]
        public listedtime[] at {
            get {
                return this.atField;
            }
            set {
                this.atField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="listed-time", Namespace="http://api.digipost.no/schema/v7")]
    public partial class listedtime {
        
        private System.DateTime timeField;
        
        private bool timeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timeSpecified {
            get {
                return this.timeFieldSpecified;
            }
            set {
                this.timeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="sms-overrides", Namespace="http://api.digipost.no/schema/v7")]
    public partial class smsoverrides {
        
        private string smsmobilenumberField;
        
        private string textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sms-mobile-number")]
        public string smsmobilenumber {
            get {
                return this.smsmobilenumberField;
            }
            set {
                this.smsmobilenumberField = value;
            }
        }
        
        /// <remarks/>
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="sms-notification", Namespace="http://api.digipost.no/schema/v7")]
    public partial class smsnotification {
        
        private smsoverrides overridesField;
        
        private listedtime[] atField;
        
        private int[] afterhoursField;
        
        /// <remarks/>
        public smsoverrides overrides {
            get {
                return this.overridesField;
            }
            set {
                this.overridesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("at")]
        public listedtime[] at {
            get {
                return this.atField;
            }
            set {
                this.atField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("after-hours")]
        public int[] afterhours {
            get {
                return this.afterhoursField;
            }
            set {
                this.afterhoursField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="foreign-address", Namespace="http://api.digipost.no/schema/v7")]
    public partial class foreignaddress {
        
        private string addressline1Field;
        
        private string addressline2Field;
        
        private string addressline3Field;
        
        private string addressline4Field;
        
        private string itemField;
        
        private ItemChoiceType2 itemElementNameField;
        
        /// <remarks/>
        public string addressline1 {
            get {
                return this.addressline1Field;
            }
            set {
                this.addressline1Field = value;
            }
        }
        
        /// <remarks/>
        public string addressline2 {
            get {
                return this.addressline2Field;
            }
            set {
                this.addressline2Field = value;
            }
        }
        
        /// <remarks/>
        public string addressline3 {
            get {
                return this.addressline3Field;
            }
            set {
                this.addressline3Field = value;
            }
        }
        
        /// <remarks/>
        public string addressline4 {
            get {
                return this.addressline4Field;
            }
            set {
                this.addressline4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("country", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("country-code", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType2 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.digipost.no/schema/v7", IncludeInSchema=false)]
    public enum ItemChoiceType2 {
        
        /// <remarks/>
        country,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("country-code")]
        countrycode,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="norwegian-address", Namespace="http://api.digipost.no/schema/v7")]
    public partial class norwegianaddress {
        
        private string addressline1Field;
        
        private string addressline2Field;
        
        private string addressline3Field;
        
        private string zipcodeField;
        
        private string cityField;
        
        /// <remarks/>
        public string addressline1 {
            get {
                return this.addressline1Field;
            }
            set {
                this.addressline1Field = value;
            }
        }
        
        /// <remarks/>
        public string addressline2 {
            get {
                return this.addressline2Field;
            }
            set {
                this.addressline2Field = value;
            }
        }
        
        /// <remarks/>
        public string addressline3 {
            get {
                return this.addressline3Field;
            }
            set {
                this.addressline3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("zip-code")]
        public string zipcode {
            get {
                return this.zipcodeField;
            }
            set {
                this.zipcodeField = value;
            }
        }
        
        /// <remarks/>
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="print-recipient", Namespace="http://api.digipost.no/schema/v7")]
    public partial class printrecipient {
        
        private string nameField;
        
        private object itemField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("foreign-address", typeof(foreignaddress))]
        [System.Xml.Serialization.XmlElementAttribute("norwegian-address", typeof(norwegianaddress))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="print-details", Namespace="http://api.digipost.no/schema/v7")]
    public partial class printdetails {
        
        private printrecipient recipientField;
        
        private printrecipient returnaddressField;
        
        private posttype posttypeField;
        
        private printcolors colorField;
        
        private nondeliverablehandling nondeliverablehandlingField;
        
        public printdetails() {
            this.colorField = printcolors.MONOCHROME;
            this.nondeliverablehandlingField = nondeliverablehandling.RETURN_TO_SENDER;
        }
        
        /// <remarks/>
        public printrecipient recipient {
            get {
                return this.recipientField;
            }
            set {
                this.recipientField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("return-address")]
        public printrecipient returnaddress {
            get {
                return this.returnaddressField;
            }
            set {
                this.returnaddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("post-type")]
        public posttype posttype {
            get {
                return this.posttypeField;
            }
            set {
                this.posttypeField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(printcolors.MONOCHROME)]
        public printcolors color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("nondeliverable-handling")]
        [System.ComponentModel.DefaultValueAttribute(nondeliverablehandling.RETURN_TO_SENDER)]
        public nondeliverablehandling nondeliverablehandling {
            get {
                return this.nondeliverablehandlingField;
            }
            set {
                this.nondeliverablehandlingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="post-type", Namespace="http://api.digipost.no/schema/v7")]
    public enum posttype {
        
        /// <remarks/>
        A,
        
        /// <remarks/>
        B,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="print-colors", Namespace="http://api.digipost.no/schema/v7")]
    public enum printcolors {
        
        /// <remarks/>
        MONOCHROME,
        
        /// <remarks/>
        COLORS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="nondeliverable-handling", Namespace="http://api.digipost.no/schema/v7")]
    public enum nondeliverablehandling {
        
        /// <remarks/>
        SHRED,
        
        /// <remarks/>
        RETURN_TO_SENDER,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="name-and-address", Namespace="http://api.digipost.no/schema/v7")]
    public partial class nameandaddress {
        
        private string fullnameField;
        
        private string addressline1Field;
        
        private string addressline2Field;
        
        private string postalcodeField;
        
        private string cityField;
        
        private System.DateTime birthdateField;
        
        private bool birthdateFieldSpecified;
        
        private string phonenumberField;
        
        private string emailaddressField;
        
        /// <remarks/>
        public string fullname {
            get {
                return this.fullnameField;
            }
            set {
                this.fullnameField = value;
            }
        }
        
        /// <remarks/>
        public string addressline1 {
            get {
                return this.addressline1Field;
            }
            set {
                this.addressline1Field = value;
            }
        }
        
        /// <remarks/>
        public string addressline2 {
            get {
                return this.addressline2Field;
            }
            set {
                this.addressline2Field = value;
            }
        }
        
        /// <remarks/>
        public string postalcode {
            get {
                return this.postalcodeField;
            }
            set {
                this.postalcodeField = value;
            }
        }
        
        /// <remarks/>
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("birth-date", DataType="date")]
        public System.DateTime birthdate {
            get {
                return this.birthdateField;
            }
            set {
                this.birthdateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool birthdateSpecified {
            get {
                return this.birthdateFieldSpecified;
            }
            set {
                this.birthdateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("phone-number")]
        public string phonenumber {
            get {
                return this.phonenumberField;
            }
            set {
                this.phonenumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("email-address")]
        public string emailaddress {
            get {
                return this.emailaddressField;
            }
            set {
                this.emailaddressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.digipost.no/schema/v7")]
    public partial class suggestion {
        
        private string searchstringField;
        
        private link linkField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("search-string")]
        public string searchstring {
            get {
                return this.searchstringField;
            }
            set {
                this.searchstringField = value;
            }
        }
        
        /// <remarks/>
        public link link {
            get {
                return this.linkField;
            }
            set {
                this.linkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.digipost.no/schema/v7")]
    public partial class address {
        
        private string streetField;
        
        private string housenumberField;
        
        private string houseletterField;
        
        private string additionaladdresslineField;
        
        private string zipcodeField;
        
        private string cityField;
        
        /// <remarks/>
        public string street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("house-number")]
        public string housenumber {
            get {
                return this.housenumberField;
            }
            set {
                this.housenumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("house-letter")]
        public string houseletter {
            get {
                return this.houseletterField;
            }
            set {
                this.houseletterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("additional-addressline")]
        public string additionaladdressline {
            get {
                return this.additionaladdresslineField;
            }
            set {
                this.additionaladdresslineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("zip-code")]
        public string zipcode {
            get {
                return this.zipcodeField;
            }
            set {
                this.zipcodeField = value;
            }
        }
        
        /// <remarks/>
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.digipost.no/schema/v7")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://api.digipost.no/schema/v7", IsNullable=false)]
    public partial class recipients {
        
        private recipient[] recipientField;
        
        private link[] linkField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("recipient")]
        public recipient[] recipient {
            get {
                return this.recipientField;
            }
            set {
                this.recipientField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("link")]
        public link[] link {
            get {
                return this.linkField;
            }
            set {
                this.linkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.digipost.no/schema/v7")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://api.digipost.no/schema/v7", IsNullable=false)]
    public partial class recipient {
        
        private string firstnameField;
        
        private string middlenameField;
        
        private string lastnameField;
        
        private string digipostaddressField;
        
        private string mobilenumberField;
        
        private string organisationnumberField;
        
        private string organisationnameField;
        
        private address[] addressField;
        
        private link[] linkField;
        
        /// <remarks/>
        public string firstname {
            get {
                return this.firstnameField;
            }
            set {
                this.firstnameField = value;
            }
        }
        
        /// <remarks/>
        public string middlename {
            get {
                return this.middlenameField;
            }
            set {
                this.middlenameField = value;
            }
        }
        
        /// <remarks/>
        public string lastname {
            get {
                return this.lastnameField;
            }
            set {
                this.lastnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("digipost-address")]
        public string digipostaddress {
            get {
                return this.digipostaddressField;
            }
            set {
                this.digipostaddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mobile-number")]
        public string mobilenumber {
            get {
                return this.mobilenumberField;
            }
            set {
                this.mobilenumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("organisation-number")]
        public string organisationnumber {
            get {
                return this.organisationnumberField;
            }
            set {
                this.organisationnumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("organisation-name")]
        public string organisationname {
            get {
                return this.organisationnameField;
            }
            set {
                this.organisationnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("address")]
        public address[] address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("link")]
        public link[] link {
            get {
                return this.linkField;
            }
            set {
                this.linkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="encryption-key", Namespace="http://api.digipost.no/schema/v7")]
    [System.Xml.Serialization.XmlRootAttribute("encryption-key", Namespace="http://api.digipost.no/schema/v7", IsNullable=false)]
    public partial class encryptionkey {
        
        private string keyidField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("key-id")]
        public string keyid {
            get {
                return this.keyidField;
            }
            set {
                this.keyidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://api.digipost.no/schema/v7")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://api.digipost.no/schema/v7", IsNullable=false)]
    public partial class autocomplete {
        
        private suggestion[] suggestionField;
        
        private link[] linkField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("suggestion")]
        public suggestion[] suggestion {
            get {
                return this.suggestionField;
            }
            set {
                this.suggestionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("link")]
        public link[] link {
            get {
                return this.linkField;
            }
            set {
                this.linkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://api.digipost.no/schema/v7")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://api.digipost.no/schema/v7", IsNullable=false)]
    public partial class error {
        
        private string errorcodeField;
        
        private string errormessageField;
        
        private string errortypeField;
        
        private link[] linkField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("error-code")]
        public string errorcode {
            get {
                return this.errorcodeField;
            }
            set {
                this.errorcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("error-message")]
        public string errormessage {
            get {
                return this.errormessageField;
            }
            set {
                this.errormessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("error-type")]
        public string errortype {
            get {
                return this.errortypeField;
            }
            set {
                this.errortypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("link")]
        public link[] link {
            get {
                return this.linkField;
            }
            set {
                this.linkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="identification-result", Namespace="http://api.digipost.no/schema/v7")]
    [System.Xml.Serialization.XmlRootAttribute("identification-result", Namespace="http://api.digipost.no/schema/v7", IsNullable=false)]
    public partial class identificationresult {
        
        private identificationresultcode resultField;
        
        private object[] itemsField;
        
        private ItemsChoiceType[] itemsElementNameField;
        
        /// <remarks/>
        public identificationresultcode result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("digipost-address", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("invalid-reason", typeof(invalidreason))]
        [System.Xml.Serialization.XmlElementAttribute("person-alias", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("unidentified-reason", typeof(unidentifiedreason))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="identification-result-code", Namespace="http://api.digipost.no/schema/v7")]
    public enum identificationresultcode {
        
        /// <remarks/>
        DIGIPOST,
        
        /// <remarks/>
        IDENTIFIED,
        
        /// <remarks/>
        UNIDENTIFIED,
        
        /// <remarks/>
        INVALID,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="invalid-reason", Namespace="http://api.digipost.no/schema/v7")]
    public enum invalidreason {
        
        /// <remarks/>
        INVALID_PERSONAL_IDENTIFICATION_NUMBER,
        
        /// <remarks/>
        INVALID_ORGANISATION_NUMBER,
        
        /// <remarks/>
        UNKNOWN,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="unidentified-reason", Namespace="http://api.digipost.no/schema/v7")]
    public enum unidentifiedreason {
        
        /// <remarks/>
        MULTIPLE_MATCHES,
        
        /// <remarks/>
        NOT_FOUND,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.digipost.no/schema/v7", IncludeInSchema=false)]
    public enum ItemsChoiceType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("digipost-address")]
        digipostaddress,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("invalid-reason")]
        invalidreason,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("person-alias")]
        personalias,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("unidentified-reason")]
        unidentifiedreason,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="identification-result-with-encryption-key", Namespace="http://api.digipost.no/schema/v7")]
    [System.Xml.Serialization.XmlRootAttribute("identification-result-with-encryption-key", Namespace="http://api.digipost.no/schema/v7", IsNullable=false)]
    public partial class identificationresultwithencryptionkey {
        
        private identificationresult identificationresultField;
        
        private encryptionkey encryptionkeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("identification-result")]
        public identificationresult identificationresult {
            get {
                return this.identificationresultField;
            }
            set {
                this.identificationresultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("encryption-key")]
        public encryptionkey encryptionkey {
            get {
                return this.encryptionkeyField;
            }
            set {
                this.encryptionkeyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.digipost.no/schema/v7")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://api.digipost.no/schema/v7", IsNullable=false)]
    public partial class identification {
        
        private object itemField;
        
        private ItemChoiceType itemElementNameField;
        
        private bool includepersonaliasfordigipostuserField;
        
        public identification() {
            this.includepersonaliasfordigipostuserField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("digipost-address", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("name-and-address", typeof(nameandaddress))]
        [System.Xml.Serialization.XmlElementAttribute("organisation-number", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("personal-identification-number", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("include-personalias-for-digipost-user")]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool includepersonaliasfordigipostuser {
            get {
                return this.includepersonaliasfordigipostuserField;
            }
            set {
                this.includepersonaliasfordigipostuserField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.digipost.no/schema/v7", IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("digipost-address")]
        digipostaddress,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("name-and-address")]
        nameandaddress,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("organisation-number")]
        organisationnumber,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("personal-identification-number")]
        personalidentificationnumber,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="message-recipient", Namespace="http://api.digipost.no/schema/v7")]
    [System.Xml.Serialization.XmlRootAttribute("message-recipient", Namespace="http://api.digipost.no/schema/v7", IsNullable=false)]
    public partial class messagerecipient {
        
        private object itemField;
        
        private ItemChoiceType1 itemElementNameField;
        
        private printdetails printdetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("digipost-address", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("name-and-address", typeof(nameandaddress))]
        [System.Xml.Serialization.XmlElementAttribute("organisation-number", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("personal-identification-number", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType1 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("print-details")]
        public printdetails printdetails {
            get {
                return this.printdetailsField;
            }
            set {
                this.printdetailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.digipost.no/schema/v7", IncludeInSchema=false)]
    public enum ItemChoiceType1 {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("digipost-address")]
        digipostaddress,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("name-and-address")]
        nameandaddress,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("organisation-number")]
        organisationnumber,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("personal-identification-number")]
        personalidentificationnumber,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="message-delivery", Namespace="http://api.digipost.no/schema/v7")]
    [System.Xml.Serialization.XmlRootAttribute("message-delivery", Namespace="http://api.digipost.no/schema/v7", IsNullable=false)]
    public partial class messagedelivery {
        
        private string messageidField;
        
        private channel deliverymethodField;
        
        private long senderidField;
        
        private messagestatus statusField;
        
        private System.DateTime deliverytimeField;
        
        private bool deliverytimeFieldSpecified;
        
        private document primarydocumentField;
        
        private document[] attachmentField;
        
        private link[] linkField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("message-id")]
        public string messageid {
            get {
                return this.messageidField;
            }
            set {
                this.messageidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("delivery-method")]
        public channel deliverymethod {
            get {
                return this.deliverymethodField;
            }
            set {
                this.deliverymethodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sender-id")]
        public long senderid {
            get {
                return this.senderidField;
            }
            set {
                this.senderidField = value;
            }
        }
        
        /// <remarks/>
        public messagestatus status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("delivery-time")]
        public System.DateTime deliverytime {
            get {
                return this.deliverytimeField;
            }
            set {
                this.deliverytimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool deliverytimeSpecified {
            get {
                return this.deliverytimeFieldSpecified;
            }
            set {
                this.deliverytimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("primary-document")]
        public document primarydocument {
            get {
                return this.primarydocumentField;
            }
            set {
                this.primarydocumentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("attachment")]
        public document[] attachment {
            get {
                return this.attachmentField;
            }
            set {
                this.attachmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("link")]
        public link[] link {
            get {
                return this.linkField;
            }
            set {
                this.linkField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.digipost.no/schema/v7")]
    public enum channel {
        
        /// <remarks/>
        PRINT,
        
        /// <remarks/>
        DIGIPOST,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="message-status", Namespace="http://api.digipost.no/schema/v7")]
    public enum messagestatus {
        
        /// <remarks/>
        NOT_COMPLETE,
        
        /// <remarks/>
        COMPLETE,
        
        /// <remarks/>
        DELIVERED,
        
        /// <remarks/>
        DELIVERED_TO_PRINT,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(invoice))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.digipost.no/schema/v7")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://api.digipost.no/schema/v7", IsNullable=false)]
    public partial class document {
        
        private string uuidField;
        
        private string subjectField;
        
        private string filetypeField;
        
        private object itemField;
        
        private smsnotification smsnotificationField;
        
        private emailnotification emailnotificationField;
        
        private authenticationlevel authenticationlevelField;
        
        private bool authenticationlevelFieldSpecified;
        
        private sensitivitylevel sensitivitylevelField;
        
        private bool sensitivitylevelFieldSpecified;
        
        private encrypted encryptedField;
        
        private contenthash contenthashField;
        
        private link[] linkField;
        
        private System.Xml.XmlElement datatypeField;
        
        private string technicaltypeField;
        
        /// <remarks/>
        public string uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
            }
        }
        
        /// <remarks/>
        public string subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("file-type")]
        public string filetype {
            get {
                return this.filetypeField;
            }
            set {
                this.filetypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("opened", typeof(bool))]
        [System.Xml.Serialization.XmlElementAttribute("opening-receipt", typeof(string))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sms-notification")]
        public smsnotification smsnotification {
            get {
                return this.smsnotificationField;
            }
            set {
                this.smsnotificationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("email-notification")]
        public emailnotification emailnotification {
            get {
                return this.emailnotificationField;
            }
            set {
                this.emailnotificationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("authentication-level")]
        public authenticationlevel authenticationlevel {
            get {
                return this.authenticationlevelField;
            }
            set {
                this.authenticationlevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool authenticationlevelSpecified {
            get {
                return this.authenticationlevelFieldSpecified;
            }
            set {
                this.authenticationlevelFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sensitivity-level")]
        public sensitivitylevel sensitivitylevel {
            get {
                return this.sensitivitylevelField;
            }
            set {
                this.sensitivitylevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sensitivitylevelSpecified {
            get {
                return this.sensitivitylevelFieldSpecified;
            }
            set {
                this.sensitivitylevelFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public encrypted encrypted {
            get {
                return this.encryptedField;
            }
            set {
                this.encryptedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("content-hash")]
        public contenthash contenthash {
            get {
                return this.contenthashField;
            }
            set {
                this.contenthashField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("link")]
        public link[] link {
            get {
                return this.linkField;
            }
            set {
                this.linkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("data-type")]
        public System.Xml.XmlElement datatype {
            get {
                return this.datatypeField;
            }
            set {
                this.datatypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("technical-type")]
        public string technicaltype {
            get {
                return this.technicaltypeField;
            }
            set {
                this.technicaltypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.digipost.no/schema/v7")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://api.digipost.no/schema/v7", IsNullable=false)]
    public partial class message {
        
        private string messageidField;
        
        private object itemField;
        
        private messagerecipient recipientField;
        
        private System.DateTime deliverytimeField;
        
        private bool deliverytimeFieldSpecified;
        
        private string invoicereferenceField;
        
        private document primarydocumentField;
        
        private document[] attachmentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("message-id")]
        public string messageid {
            get {
                return this.messageidField;
            }
            set {
                this.messageidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sender-id", typeof(long))]
        [System.Xml.Serialization.XmlElementAttribute("sender-organization", typeof(senderorganization))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        public messagerecipient recipient {
            get {
                return this.recipientField;
            }
            set {
                this.recipientField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("delivery-time")]
        public System.DateTime deliverytime {
            get {
                return this.deliverytimeField;
            }
            set {
                this.deliverytimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool deliverytimeSpecified {
            get {
                return this.deliverytimeFieldSpecified;
            }
            set {
                this.deliverytimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("invoice-reference")]
        public string invoicereference {
            get {
                return this.invoicereferenceField;
            }
            set {
                this.invoicereferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("primary-document")]
        public document primarydocument {
            get {
                return this.primarydocumentField;
            }
            set {
                this.primarydocumentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("attachment")]
        public document[] attachment {
            get {
                return this.attachmentField;
            }
            set {
                this.attachmentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.digipost.no/schema/v7")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://api.digipost.no/schema/v7", IsNullable=false)]
    public partial class invoice : document {
        
        private string kidField;
        
        private decimal amountField;
        
        private string accountField;
        
        private System.DateTime duedateField;
        
        /// <remarks/>
        public string kid {
            get {
                return this.kidField;
            }
            set {
                this.kidField = value;
            }
        }
        
        /// <remarks/>
        public decimal amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public string account {
            get {
                return this.accountField;
            }
            set {
                this.accountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("due-date", DataType="date")]
        public System.DateTime duedate {
            get {
                return this.duedateField;
            }
            set {
                this.duedateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="sender-information", Namespace="http://api.digipost.no/schema/v7")]
    [System.Xml.Serialization.XmlRootAttribute("sender-information", Namespace="http://api.digipost.no/schema/v7", IsNullable=false)]
    public partial class senderinformation {
        
        private long senderidField;
        
        private bool senderidFieldSpecified;
        
        private senderstatus statusField;
        
        private feature[] supportedfeaturesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sender-id")]
        public long senderid {
            get {
                return this.senderidField;
            }
            set {
                this.senderidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool senderidSpecified {
            get {
                return this.senderidFieldSpecified;
            }
            set {
                this.senderidFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public senderstatus status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("supported-features")]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public feature[] supportedfeatures {
            get {
                return this.supportedfeaturesField;
            }
            set {
                this.supportedfeaturesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="sender-status", Namespace="http://api.digipost.no/schema/v7")]
    public enum senderstatus {
        
        /// <remarks/>
        NO_INFO_AVAILABLE,
        
        /// <remarks/>
        VALID_SENDER,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="document-status", Namespace="http://api.digipost.no/schema/v7")]
    [System.Xml.Serialization.XmlRootAttribute("document-status", Namespace="http://api.digipost.no/schema/v7", IsNullable=false)]
    public partial class documentstatus {
        
        private documentstatus[] attachmentsField;
        
        private link[] linkField;
        
        private string uuidField;
        
        private long senderidField;
        
        private bool senderidFieldSpecified;
        
        private deliverystatus statusField;
        
        private bool statusFieldSpecified;
        
        private System.DateTime createdField;
        
        private bool createdFieldSpecified;
        
        private System.DateTime deliveredField;
        
        private bool deliveredFieldSpecified;
        
        private read readField;
        
        private bool readFieldSpecified;
        
        private channel channelField;
        
        private bool channelFieldSpecified;
        
        private bool isprimarydocumentField;
        
        private bool isprimarydocumentFieldSpecified;
        
        private string contenthashField;
        
        private hashalgorithm contenthashalgorithmField;
        
        private bool contenthashalgorithmFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("attachments")]
        public documentstatus[] attachments {
            get {
                return this.attachmentsField;
            }
            set {
                this.attachmentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("link")]
        public link[] link {
            get {
                return this.linkField;
            }
            set {
                this.linkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("sender-id")]
        public long senderid {
            get {
                return this.senderidField;
            }
            set {
                this.senderidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool senderidSpecified {
            get {
                return this.senderidFieldSpecified;
            }
            set {
                this.senderidFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public deliverystatus status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool createdSpecified {
            get {
                return this.createdFieldSpecified;
            }
            set {
                this.createdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime delivered {
            get {
                return this.deliveredField;
            }
            set {
                this.deliveredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool deliveredSpecified {
            get {
                return this.deliveredFieldSpecified;
            }
            set {
                this.deliveredFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public read read {
            get {
                return this.readField;
            }
            set {
                this.readField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool readSpecified {
            get {
                return this.readFieldSpecified;
            }
            set {
                this.readFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public channel channel {
            get {
                return this.channelField;
            }
            set {
                this.channelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool channelSpecified {
            get {
                return this.channelFieldSpecified;
            }
            set {
                this.channelFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("is-primary-document")]
        public bool isprimarydocument {
            get {
                return this.isprimarydocumentField;
            }
            set {
                this.isprimarydocumentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isprimarydocumentSpecified {
            get {
                return this.isprimarydocumentFieldSpecified;
            }
            set {
                this.isprimarydocumentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("content-hash")]
        public string contenthash {
            get {
                return this.contenthashField;
            }
            set {
                this.contenthashField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("content-hash-algorithm")]
        public hashalgorithm contenthashalgorithm {
            get {
                return this.contenthashalgorithmField;
            }
            set {
                this.contenthashalgorithmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool contenthashalgorithmSpecified {
            get {
                return this.contenthashalgorithmFieldSpecified;
            }
            set {
                this.contenthashalgorithmFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="delivery-status", Namespace="http://api.digipost.no/schema/v7")]
    public enum deliverystatus {
        
        /// <remarks/>
        DELIVERED,
        
        /// <remarks/>
        NOT_DELIVERED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.digipost.no/schema/v7")]
    public enum read {
        
        /// <remarks/>
        Y,
        
        /// <remarks/>
        N,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="hash-algorithm", Namespace="http://api.digipost.no/schema/v7")]
    public enum hashalgorithm {
        
        /// <remarks/>
        NONE,
        
        /// <remarks/>
        MD5,
        
        /// <remarks/>
        SHA256,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="document-events", Namespace="http://api.digipost.no/schema/v7")]
    [System.Xml.Serialization.XmlRootAttribute("document-events", Namespace="http://api.digipost.no/schema/v7", IsNullable=false)]
    public partial class documentevents {
        
        private @event[] eventField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("event")]
        public @event[] @event {
            get {
                return this.eventField;
            }
            set {
                this.eventField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.digipost.no/schema/v7")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://api.digipost.no/schema/v7", IsNullable=false)]
    public partial class inbox {
        
        private inboxdocument[] documentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("document")]
        public inboxdocument[] document {
            get {
                return this.documentField;
            }
            set {
                this.documentField = value;
            }
        }
    }
}
