//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//This source code was auto-generated by MonoXSD
//


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.digipost.no/schema/datatypes")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://api.digipost.no/schema/datatypes", IsNullable=false)]
public partial class appointment {
    
    private string starttimeField;
    
    private string endtimeField;
    
    private string arrivaltimeField;
    
    private string placeField;
    
    private datatypeaddress addressField;
    
    private string subtitleField;
    
    private info[] infoField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("start-time")]
    public string starttime {
        get {
            return this.starttimeField;
        }
        set {
            this.starttimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("end-time")]
    public string endtime {
        get {
            return this.endtimeField;
        }
        set {
            this.endtimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("arrival-time")]
    public string arrivaltime {
        get {
            return this.arrivaltimeField;
        }
        set {
            this.arrivaltimeField = value;
        }
    }
    
    /// <remarks/>
    public string place {
        get {
            return this.placeField;
        }
        set {
            this.placeField = value;
        }
    }
    
    /// <remarks/>
    public datatypeaddress address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("sub-title")]
    public string subtitle {
        get {
            return this.subtitleField;
        }
        set {
            this.subtitleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("info")]
    public info[] info {
        get {
            return this.infoField;
        }
        set {
            this.infoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.digipost.no/schema/datatypes")]
public partial class datatypeaddress {
    
    private string streetaddressField;
    
    private string streetaddress2Field;
    
    private string postalcodeField;
    
    private string cityField;
    
    private string countryField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("street-address")]
    public string streetaddress {
        get {
            return this.streetaddressField;
        }
        set {
            this.streetaddressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("street-address-2")]
    public string streetaddress2 {
        get {
            return this.streetaddress2Field;
        }
        set {
            this.streetaddress2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("postal-code")]
    public string postalcode {
        get {
            return this.postalcodeField;
        }
        set {
            this.postalcodeField = value;
        }
    }
    
    /// <remarks/>
    public string city {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    public string country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.digipost.no/schema/datatypes")]
public partial class delivery {
    
    private string nameField;
    
    private datatypeaddress addressField;
    
    private string termsField;
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public datatypeaddress address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
    
    /// <remarks/>
    public string terms {
        get {
            return this.termsField;
        }
        set {
            this.termsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.digipost.no/schema/datatypes")]
public partial class customer {
    
    private string nameField;
    
    private datatypeaddress addressField;
    
    private string phoneNumberField;
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public datatypeaddress address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
    
    /// <remarks/>
    public string phoneNumber {
        get {
            return this.phoneNumberField;
        }
        set {
            this.phoneNumberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.digipost.no/schema/datatypes")]
public partial class vatLevel {
    
    private string grossAmountField;
    
    private string netAmountField;
    
    private string vatField;
    
    private string vatPercentField;
    
    /// <remarks/>
    public string grossAmount {
        get {
            return this.grossAmountField;
        }
        set {
            this.grossAmountField = value;
        }
    }
    
    /// <remarks/>
    public string netAmount {
        get {
            return this.netAmountField;
        }
        set {
            this.netAmountField = value;
        }
    }
    
    /// <remarks/>
    public string vat {
        get {
            return this.vatField;
        }
        set {
            this.vatField = value;
        }
    }
    
    /// <remarks/>
    public string vatPercent {
        get {
            return this.vatPercentField;
        }
        set {
            this.vatPercentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.digipost.no/schema/datatypes")]
public partial class vatDetails {
    
    private vatLevel[] levelsField;
    
    private string sumField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("levels")]
    public vatLevel[] levels {
        get {
            return this.levelsField;
        }
        set {
            this.levelsField = value;
        }
    }
    
    /// <remarks/>
    public string sum {
        get {
            return this.sumField;
        }
        set {
            this.sumField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.digipost.no/schema/datatypes")]
public partial class taxiDetails {
    
    private string carPlateNumberField;
    
    private string licenseField;
    
    private string orgNumberLicenseHolderField;
    
    private string startTimeField;
    
    private string stopTimeField;
    
    private string tipsField;
    
    private string totalMeterPriceField;
    
    private System.Nullable<int> totalDistanceBeforeBoardingInMetersField;
    
    private System.Nullable<int> totalDistanceInMetersField;
    
    private System.Nullable<int> totalDistanceWithPassengerInMetersField;
    
    private System.Nullable<int> totalTimeBeforeBoardingInSecondsField;
    
    private System.Nullable<int> totalTimeInSecondsField;
    
    private System.Nullable<int> totalTimeWithPassengerInSecondsField;
    
    private vatDetails vatField;
    
    /// <remarks/>
    public string carPlateNumber {
        get {
            return this.carPlateNumberField;
        }
        set {
            this.carPlateNumberField = value;
        }
    }
    
    /// <remarks/>
    public string license {
        get {
            return this.licenseField;
        }
        set {
            this.licenseField = value;
        }
    }
    
    /// <remarks/>
    public string orgNumberLicenseHolder {
        get {
            return this.orgNumberLicenseHolderField;
        }
        set {
            this.orgNumberLicenseHolderField = value;
        }
    }
    
    /// <remarks/>
    public string startTime {
        get {
            return this.startTimeField;
        }
        set {
            this.startTimeField = value;
        }
    }
    
    /// <remarks/>
    public string stopTime {
        get {
            return this.stopTimeField;
        }
        set {
            this.stopTimeField = value;
        }
    }
    
    /// <remarks/>
    public string tips {
        get {
            return this.tipsField;
        }
        set {
            this.tipsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string totalMeterPrice {
        get {
            return this.totalMeterPriceField;
        }
        set {
            this.totalMeterPriceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> totalDistanceBeforeBoardingInMeters {
        get {
            return this.totalDistanceBeforeBoardingInMetersField;
        }
        set {
            this.totalDistanceBeforeBoardingInMetersField = value;
        }
    }
    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> totalDistanceInMeters {
        get {
            return this.totalDistanceInMetersField;
        }
        set {
            this.totalDistanceInMetersField = value;
        }
    }
    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> totalDistanceWithPassengerInMeters {
        get {
            return this.totalDistanceWithPassengerInMetersField;
        }
        set {
            this.totalDistanceWithPassengerInMetersField = value;
        }
    }
    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> totalTimeBeforeBoardingInSeconds {
        get {
            return this.totalTimeBeforeBoardingInSecondsField;
        }
        set {
            this.totalTimeBeforeBoardingInSecondsField = value;
        }
    }
    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> totalTimeInSeconds {
        get {
            return this.totalTimeInSecondsField;
        }
        set {
            this.totalTimeInSecondsField = value;
        }
    }

    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> totalTimeWithPassengerInSeconds {
        get {
            return this.totalTimeWithPassengerInSecondsField;
        }
        set {
            this.totalTimeWithPassengerInSecondsField = value;
        }
    }
    
    
    /// <remarks/>
    public vatDetails vat {
        get {
            return this.vatField;
        }
        set {
            this.vatField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.digipost.no/schema/datatypes")]
public partial class receiptLine {
    
    private string itemnameField;
    
    private string itemdescriptionField;
    
    private string itemcodeField;
    
    private string unitField;
    
    private double quantityField;
    
    private string itempriceField;
    
    private string itemvatField;
    
    private string totalpriceField;
    
    private string totalvatField;
    
    private string discountField;
    
    private string serialNumberField;
    
    private string eanCodeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("item-name")]
    public string itemname {
        get {
            return this.itemnameField;
        }
        set {
            this.itemnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("item-description")]
    public string itemdescription {
        get {
            return this.itemdescriptionField;
        }
        set {
            this.itemdescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("item-code")]
    public string itemcode {
        get {
            return this.itemcodeField;
        }
        set {
            this.itemcodeField = value;
        }
    }
    
    /// <remarks/>
    public string unit {
        get {
            return this.unitField;
        }
        set {
            this.unitField = value;
        }
    }
    
    /// <remarks/>
    public double quantity {
        get {
            return this.quantityField;
        }
        set {
            this.quantityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("item-price")]
    public string itemprice {
        get {
            return this.itempriceField;
        }
        set {
            this.itempriceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("item-vat")]
    public string itemvat {
        get {
            return this.itemvatField;
        }
        set {
            this.itemvatField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("total-price")]
    public string totalprice {
        get {
            return this.totalpriceField;
        }
        set {
            this.totalpriceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("total-vat")]
    public string totalvat {
        get {
            return this.totalvatField;
        }
        set {
            this.totalvatField = value;
        }
    }
    
    /// <remarks/>
    public string discount {
        get {
            return this.discountField;
        }
        set {
            this.discountField = value;
        }
    }
    
    /// <remarks/>
    public string serialNumber {
        get {
            return this.serialNumberField;
        }
        set {
            this.serialNumberField = value;
        }
    }
    
    /// <remarks/>
    public string eanCode {
        get {
            return this.eanCodeField;
        }
        set {
            this.eanCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.digipost.no/schema/datatypes")]
public partial class foreignCurrencyPayment {
    
    private string currencycodeField;
    
    private System.Nullable<decimal> amountField;
    
    private System.Nullable<decimal> exchangerateField;
    
    private string labelField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("currency-code")]
    public string currencycode {
        get {
            return this.currencycodeField;
        }
        set {
            this.currencycodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> amount {
        get {
            return this.amountField;
        }
        set {
            this.amountField = value;
        }
    }
    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("exchange-rate", IsNullable=true)]
    public System.Nullable<decimal> exchangerate {
        get {
            return this.exchangerateField;
        }
        set {
            this.exchangerateField = value;
        }
    }
    
    
    /// <remarks/>
    public string label {
        get {
            return this.labelField;
        }
        set {
            this.labelField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.digipost.no/schema/datatypes")]
public partial class payment {
    
    private string typeField;
    
    private string cardnumberField;
    
    private string cardNameField;
    
    private string amountField;
    
    private string currencycodeField;
    
    private foreignCurrencyPayment foreigncurrencypaymentField;
    
    /// <remarks/>
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("card-number")]
    public string cardnumber {
        get {
            return this.cardnumberField;
        }
        set {
            this.cardnumberField = value;
        }
    }
    
    /// <remarks/>
    public string cardName {
        get {
            return this.cardNameField;
        }
        set {
            this.cardNameField = value;
        }
    }
    
    /// <remarks/>
    public string amount {
        get {
            return this.amountField;
        }
        set {
            this.amountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("currency-code")]
    public string currencycode {
        get {
            return this.currencycodeField;
        }
        set {
            this.currencycodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("foreign-currency-payment")]
    public foreignCurrencyPayment foreigncurrencypayment {
        get {
            return this.foreigncurrencypaymentField;
        }
        set {
            this.foreigncurrencypaymentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.digipost.no/schema/datatypes")]
public partial class proofHolder {
    
    private string firstnameField;
    
    private string surnameField;
    
    private string socialsecuritynumberField;
    
    private datatypeaddress addressField;
    
    /// <remarks/>
    public string firstname {
        get {
            return this.firstnameField;
        }
        set {
            this.firstnameField = value;
        }
    }
    
    /// <remarks/>
    public string surname {
        get {
            return this.surnameField;
        }
        set {
            this.surnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("social-security-number")]
    public string socialsecuritynumber {
        get {
            return this.socialsecuritynumberField;
        }
        set {
            this.socialsecuritynumberField = value;
        }
    }
    
    /// <remarks/>
    public datatypeaddress address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.digipost.no/schema/datatypes")]
public partial class calendarDate {
    
    private int monthField;
    
    private int dayField;
    
    private int hourField;
    
    private int minField;
    
    private string timezoneField;
    
    public calendarDate() {
        this.hourField = 0;
        this.minField = 0;
        this.timezoneField = "+01:00";
    }
    
    /// <remarks/>
    public int month {
        get {
            return this.monthField;
        }
        set {
            this.monthField = value;
        }
    }
    
    /// <remarks/>
    public int day {
        get {
            return this.dayField;
        }
        set {
            this.dayField = value;
        }
    }
    
    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute(0)]
    public int hour {
        get {
            return this.hourField;
        }
        set {
            this.hourField = value;
        }
    }
    
    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute(0)]
    public int min {
        get {
            return this.minField;
        }
        set {
            this.minField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("time-zone")]
    [System.ComponentModel.DefaultValueAttribute("+01:00")]
    public string timezone {
        get {
            return this.timezoneField;
        }
        set {
            this.timezoneField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.digipost.no/schema/datatypes")]
public partial class yearlyRepeatingPeriod {
    
    private System.Nullable<int> startyearField;
    
    private System.Nullable<int> endyearField;
    
    private calendarDate fromField;
    
    private calendarDate toField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("start-year", IsNullable=true)]
    public System.Nullable<int> startyear {
        get {
            return this.startyearField;
        }
        set {
            this.startyearField = value;
        }
    }
    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("end-year", IsNullable=true)]
    public System.Nullable<int> endyear {
        get {
            return this.endyearField;
        }
        set {
            this.endyearField = value;
        }
    }
    
    
    /// <remarks/>
    public calendarDate from {
        get {
            return this.fromField;
        }
        set {
            this.fromField = value;
        }
    }
    
    /// <remarks/>
    public calendarDate to {
        get {
            return this.toField;
        }
        set {
            this.toField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.digipost.no/schema/datatypes")]
public partial class period {
    
    private string fromField;
    
    private string toField;
    
    /// <remarks/>
    public string from {
        get {
            return this.fromField;
        }
        set {
            this.fromField = value;
        }
    }
    
    /// <remarks/>
    public string to {
        get {
            return this.toField;
        }
        set {
            this.toField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.digipost.no/schema/datatypes")]
public partial class validPeriod {
    
    private object itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("period", typeof(period))]
    [System.Xml.Serialization.XmlElementAttribute("yearly-repeating-period", typeof(yearlyRepeatingPeriod))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.digipost.no/schema/datatypes")]
public partial class cost {
    
    private decimal valuetobepayedField;
    
    private System.Nullable<decimal> packagevalueField;
    
    private System.Nullable<decimal> customsfeeoutlayedField;
    
    private string vastextField;
    
    private System.Nullable<decimal> customsfeeField;
    
    private System.Nullable<decimal> customsfeeoutlaycostField;
    
    private System.Nullable<decimal> codamountField;
    
    private System.Nullable<decimal> codfeeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("value-to-be-payed")]
    public decimal valuetobepayed {
        get {
            return this.valuetobepayedField;
        }
        set {
            this.valuetobepayedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("package-value", IsNullable=true)]
    public System.Nullable<decimal> packagevalue {
        get {
            return this.packagevalueField;
        }
        set {
            this.packagevalueField = value;
        }
    }
    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("customs-fee-outlayed", IsNullable=true)]
    public System.Nullable<decimal> customsfeeoutlayed {
        get {
            return this.customsfeeoutlayedField;
        }
        set {
            this.customsfeeoutlayedField = value;
        }
    }
    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("vas-text")]
    public string vastext {
        get {
            return this.vastextField;
        }
        set {
            this.vastextField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("customs-fee", IsNullable=true)]
    public System.Nullable<decimal> customsfee {
        get {
            return this.customsfeeField;
        }
        set {
            this.customsfeeField = value;
        }
    }
    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("customs-fee-outlay-cost", IsNullable=true)]
    public System.Nullable<decimal> customsfeeoutlaycost {
        get {
            return this.customsfeeoutlaycostField;
        }
        set {
            this.customsfeeoutlaycostField = value;
        }
    }
    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("cod-amount", IsNullable=true)]
    public System.Nullable<decimal> codamount {
        get {
            return this.codamountField;
        }
        set {
            this.codamountField = value;
        }
    }
    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("cod-fee", IsNullable=true)]
    public System.Nullable<decimal> codfee {
        get {
            return this.codfeeField;
        }
        set {
            this.codfeeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.digipost.no/schema/datatypes")]
public partial class package {
    
    private System.Nullable<int> lengthField;
    
    private System.Nullable<int> widthField;
    
    private System.Nullable<int> heightField;
    
    private System.Nullable<int> weightField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> length {
        get {
            return this.lengthField;
        }
        set {
            this.lengthField = value;
        }
    }
    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> height {
        get {
            return this.heightField;
        }
        set {
            this.heightField = value;
        }
    }
    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> weight {
        get {
            return this.weightField;
        }
        set {
            this.weightField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.digipost.no/schema/datatypes")]
public partial class pickupPlace {
    
    private string nameField;
    
    private string codeField;
    
    private string instructionField;
    
    private string shelflocationField;
    
    private datatypeaddress addressField;
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    public string instruction {
        get {
            return this.instructionField;
        }
        set {
            this.instructionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("shelf-location")]
    public string shelflocation {
        get {
            return this.shelflocationField;
        }
        set {
            this.shelflocationField = value;
        }
    }
    
    /// <remarks/>
    public datatypeaddress address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.digipost.no/schema/datatypes")]
public partial class sender {
    
    private string nameField;
    
    private string referenceField;
    
    private datatypeaddress addressField;
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string reference {
        get {
            return this.referenceField;
        }
        set {
            this.referenceField = value;
        }
    }
    
    /// <remarks/>
    public datatypeaddress address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.digipost.no/schema/datatypes")]
public partial class datatyperecipient {
    
    private string nameField;
    
    private string digipostaddressField;
    
    private datatypeaddress addressField;
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("digipost-address")]
    public string digipostaddress {
        get {
            return this.digipostaddressField;
        }
        set {
            this.digipostaddressField = value;
        }
    }
    
    /// <remarks/>
    public datatypeaddress address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.digipost.no/schema/datatypes")]
public partial class barcode {
    
    private string barcodevalueField;
    
    private string barcodetypeField;
    
    private string barcodetextField;
    
    private bool showvalueinbarcodeField;
    
    public barcode() {
        this.showvalueinbarcodeField = false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("barcode-value")]
    public string barcodevalue {
        get {
            return this.barcodevalueField;
        }
        set {
            this.barcodevalueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("barcode-type")]
    public string barcodetype {
        get {
            return this.barcodetypeField;
        }
        set {
            this.barcodetypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("barcode-text")]
    public string barcodetext {
        get {
            return this.barcodetextField;
        }
        set {
            this.barcodetextField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("show-value-in-barcode")]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool showvalueinbarcode {
        get {
            return this.showvalueinbarcodeField;
        }
        set {
            this.showvalueinbarcodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.digipost.no/schema/datatypes")]
public partial class timeInterval {
    
    private string starttimeField;
    
    private string endtimeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("start-time")]
    public string starttime {
        get {
            return this.starttimeField;
        }
        set {
            this.starttimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("end-time")]
    public string endtime {
        get {
            return this.endtimeField;
        }
        set {
            this.endtimeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.digipost.no/schema/datatypes")]
public partial class heftelse {
    
    private string panthaverField;
    
    private string typepantField;
    
    private string beloepField;
    
    /// <remarks/>
    public string panthaver {
        get {
            return this.panthaverField;
        }
        set {
            this.panthaverField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("type-pant")]
    public string typepant {
        get {
            return this.typepantField;
        }
        set {
            this.typepantField = value;
        }
    }
    
    /// <remarks/>
    public string beloep {
        get {
            return this.beloepField;
        }
        set {
            this.beloepField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.digipost.no/schema/datatypes")]
public partial class omsetningshistorikk {
    
    private string datoField;
    
    private string beskrivelseField;
    
    private string selgerField;
    
    private string kjoeperField;
    
    private System.Nullable<long> beloepField;
    
    /// <remarks/>
    public string dato {
        get {
            return this.datoField;
        }
        set {
            this.datoField = value;
        }
    }
    
    /// <remarks/>
    public string beskrivelse {
        get {
            return this.beskrivelseField;
        }
        set {
            this.beskrivelseField = value;
        }
    }
    
    /// <remarks/>
    public string selger {
        get {
            return this.selgerField;
        }
        set {
            this.selgerField = value;
        }
    }
    
    /// <remarks/>
    public string kjoeper {
        get {
            return this.kjoeperField;
        }
        set {
            this.kjoeperField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<long> beloep {
        get {
            return this.beloepField;
        }
        set {
            this.beloepField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.digipost.no/schema/datatypes")]
public partial class hjemmelshaver {
    
    private string nameField;
    
    private string emailField;
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.digipost.no/schema/datatypes")]
public partial class matrikkel {
    
    private string kommunenummerField;
    
    private string gaardsnummerField;
    
    private string bruksnummerField;
    
    private string festenummerField;
    
    private string seksjonsnummerField;
    
    /// <remarks/>
    public string kommunenummer {
        get {
            return this.kommunenummerField;
        }
        set {
            this.kommunenummerField = value;
        }
    }
    
    /// <remarks/>
    public string gaardsnummer {
        get {
            return this.gaardsnummerField;
        }
        set {
            this.gaardsnummerField = value;
        }
    }
    
    /// <remarks/>
    public string bruksnummer {
        get {
            return this.bruksnummerField;
        }
        set {
            this.bruksnummerField = value;
        }
    }
    
    /// <remarks/>
    public string festenummer {
        get {
            return this.festenummerField;
        }
        set {
            this.festenummerField = value;
        }
    }
    
    /// <remarks/>
    public string seksjonsnummer {
        get {
            return this.seksjonsnummerField;
        }
        set {
            this.seksjonsnummerField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.digipost.no/schema/datatypes")]
public partial class residenceAddress {
    
    private string unitnumberField;
    
    private string housenumberField;
    
    private string streetnameField;
    
    private string postalcodeField;
    
    private string cityField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("unit-number")]
    public string unitnumber {
        get {
            return this.unitnumberField;
        }
        set {
            this.unitnumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("house-number")]
    public string housenumber {
        get {
            return this.housenumberField;
        }
        set {
            this.housenumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("street-name")]
    public string streetname {
        get {
            return this.streetnameField;
        }
        set {
            this.streetnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("postal-code")]
    public string postalcode {
        get {
            return this.postalcodeField;
        }
        set {
            this.postalcodeField = value;
        }
    }
    
    /// <remarks/>
    public string city {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.digipost.no/schema/datatypes")]
public partial class info {
    
    private string titleField;
    
    private string textField;
    
    /// <remarks/>
    public string title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    public string text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.digipost.no/schema/datatypes")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://api.digipost.no/schema/datatypes", IsNullable=false)]
public partial class boligdetaljer {
    
    private residence residenceField;
    
    private hjemmelshaver[] hjemmelshavereField;
    
    private System.Nullable<int> bruksarealField;
    
    private System.Nullable<int> antalloppholdsromField;
    
    private System.Nullable<int> antallbaderomField;
    
    private omsetningshistorikk[] omsetningshistorikkField;
    
    private string organisasjonsnummerField;
    
    private string bruksenhetField;
    
    private string andelsnummerField;
    
    private heftelse[] heftelserField;
    
    private externalLink callToActionField;
    
    /// <remarks/>
    public residence residence {
        get {
            return this.residenceField;
        }
        set {
            this.residenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("hjemmelshavere")]
    public hjemmelshaver[] hjemmelshavere {
        get {
            return this.hjemmelshavereField;
        }
        set {
            this.hjemmelshavereField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> bruksareal {
        get {
            return this.bruksarealField;
        }
        set {
            this.bruksarealField = value;
        }
    }
    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("antall-oppholdsrom", IsNullable=true)]
    public System.Nullable<int> antalloppholdsrom {
        get {
            return this.antalloppholdsromField;
        }
        set {
            this.antalloppholdsromField = value;
        }
    }
    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("antall-baderom", IsNullable=true)]
    public System.Nullable<int> antallbaderom {
        get {
            return this.antallbaderomField;
        }
        set {
            this.antallbaderomField = value;
        }
    }

    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("omsetningshistorikk")]
    public omsetningshistorikk[] omsetningshistorikk {
        get {
            return this.omsetningshistorikkField;
        }
        set {
            this.omsetningshistorikkField = value;
        }
    }
    
    /// <remarks/>
    public string organisasjonsnummer {
        get {
            return this.organisasjonsnummerField;
        }
        set {
            this.organisasjonsnummerField = value;
        }
    }
    
    /// <remarks/>
    public string bruksenhet {
        get {
            return this.bruksenhetField;
        }
        set {
            this.bruksenhetField = value;
        }
    }
    
    /// <remarks/>
    public string andelsnummer {
        get {
            return this.andelsnummerField;
        }
        set {
            this.andelsnummerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("heftelser")]
    public heftelse[] heftelser {
        get {
            return this.heftelserField;
        }
        set {
            this.heftelserField = value;
        }
    }
    
    /// <remarks/>
    public externalLink callToAction {
        get {
            return this.callToActionField;
        }
        set {
            this.callToActionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.digipost.no/schema/datatypes")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://api.digipost.no/schema/datatypes", IsNullable=false)]
public partial class residence {
    
    private residenceAddress addressField;
    
    private matrikkel matrikkelField;
    
    private string sourceField;
    
    private string externalidField;
    
    /// <remarks/>
    public residenceAddress address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
    
    /// <remarks/>
    public matrikkel matrikkel {
        get {
            return this.matrikkelField;
        }
        set {
            this.matrikkelField = value;
        }
    }
    
    /// <remarks/>
    public string source {
        get {
            return this.sourceField;
        }
        set {
            this.sourceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("external-id")]
    public string externalid {
        get {
            return this.externalidField;
        }
        set {
            this.externalidField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.digipost.no/schema/datatypes")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://api.digipost.no/schema/datatypes", IsNullable=false)]
public partial class externalLink {
    
    private string urlField;
    
    private System.Nullable<System.DateTime> deadlineField;
    
    private string descriptionField;
    
    private string buttontextField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
    public string url {
        get {
            return this.urlField;
        }
        set {
            this.urlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> deadline {
        get {
            return this.deadlineField;
        }
        set {
            this.deadlineField = value;
        }
    }
    
    
    /// <remarks/>
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("button-text")]
    public string buttontext {
        get {
            return this.buttontextField;
        }
        set {
            this.buttontextField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.digipost.no/schema/datatypes")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://api.digipost.no/schema/datatypes", IsNullable=false)]
public partial class @event {
    
    private string subtitleField;
    
    private timeInterval[] starttimeField;
    
    private string timeLabelField;
    
    private string descriptionField;
    
    private string placeField;
    
    private string placeLabelField;
    
    private datatypeaddress addressField;
    
    private info[] infoField;
    
    private string barcodeLabelField;
    
    private barcode barcodeField;
    
    private externalLink[] linksField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("sub-title")]
    public string subtitle {
        get {
            return this.subtitleField;
        }
        set {
            this.subtitleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("start-time")]
    public timeInterval[] starttime {
        get {
            return this.starttimeField;
        }
        set {
            this.starttimeField = value;
        }
    }
    
    /// <remarks/>
    public string timeLabel {
        get {
            return this.timeLabelField;
        }
        set {
            this.timeLabelField = value;
        }
    }
    
    /// <remarks/>
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public string place {
        get {
            return this.placeField;
        }
        set {
            this.placeField = value;
        }
    }
    
    /// <remarks/>
    public string placeLabel {
        get {
            return this.placeLabelField;
        }
        set {
            this.placeLabelField = value;
        }
    }
    
    /// <remarks/>
    public datatypeaddress address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("info")]
    public info[] info {
        get {
            return this.infoField;
        }
        set {
            this.infoField = value;
        }
    }
    
    /// <remarks/>
    public string barcodeLabel {
        get {
            return this.barcodeLabelField;
        }
        set {
            this.barcodeLabelField = value;
        }
    }
    
    /// <remarks/>
    public barcode barcode {
        get {
            return this.barcodeField;
        }
        set {
            this.barcodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("links")]
    public externalLink[] links {
        get {
            return this.linksField;
        }
        set {
            this.linksField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.digipost.no/schema/datatypes")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://api.digipost.no/schema/datatypes", IsNullable=false)]
public partial class payslip {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.digipost.no/schema/datatypes")]
[System.Xml.Serialization.XmlRootAttribute("pickup-notice", Namespace="http://api.digipost.no/schema/datatypes", IsNullable=false)]
public partial class pickupNotice {
    
    private string parcelidField;
    
    private string parceluuidField;
    
    private barcode barcodeField;
    
    private string productnameField;
    
    private string arrivaldatetimeField;
    
    private string returndatetimeField;
    
    private datatyperecipient recipientField;
    
    private sender senderField;
    
    private pickupPlace pickupplaceField;
    
    private package packageField;
    
    private cost costField;
    
    private status statusField;
    
    private tag[] tagsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("parcel-id")]
    public string parcelid {
        get {
            return this.parcelidField;
        }
        set {
            this.parcelidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("parcel-uuid")]
    public string parceluuid {
        get {
            return this.parceluuidField;
        }
        set {
            this.parceluuidField = value;
        }
    }
    
    /// <remarks/>
    public barcode barcode {
        get {
            return this.barcodeField;
        }
        set {
            this.barcodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("product-name")]
    public string productname {
        get {
            return this.productnameField;
        }
        set {
            this.productnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("arrival-date-time")]
    public string arrivaldatetime {
        get {
            return this.arrivaldatetimeField;
        }
        set {
            this.arrivaldatetimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("return-date-time")]
    public string returndatetime {
        get {
            return this.returndatetimeField;
        }
        set {
            this.returndatetimeField = value;
        }
    }
    
    /// <remarks/>
    public datatyperecipient recipient {
        get {
            return this.recipientField;
        }
        set {
            this.recipientField = value;
        }
    }
    
    /// <remarks/>
    public sender sender {
        get {
            return this.senderField;
        }
        set {
            this.senderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("pickup-place")]
    public pickupPlace pickupplace {
        get {
            return this.pickupplaceField;
        }
        set {
            this.pickupplaceField = value;
        }
    }
    
    /// <remarks/>
    public package package {
        get {
            return this.packageField;
        }
        set {
            this.packageField = value;
        }
    }
    
    /// <remarks/>
    public cost cost {
        get {
            return this.costField;
        }
        set {
            this.costField = value;
        }
    }
    
    /// <remarks/>
    public status status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("tags")]
    public tag[] tags {
        get {
            return this.tagsField;
        }
        set {
            this.tagsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.digipost.no/schema/datatypes")]
public enum status {
    
    /// <remarks/>
    READY_FOR_PICKUP,
    
    /// <remarks/>
    RETURNED,
    
    /// <remarks/>
    UNKNOWN,
    
    /// <remarks/>
    DEVIATION,
    
    /// <remarks/>
    PICKED_UP,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.digipost.no/schema/datatypes")]
public enum tag {
    
    /// <remarks/>
    POSTEN,
    
    /// <remarks/>
    VARSEL2,
    
    /// <remarks/>
    VARSEL1,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.digipost.no/schema/datatypes")]
[System.Xml.Serialization.XmlRootAttribute("pickup-notice-status", Namespace="http://api.digipost.no/schema/datatypes", IsNullable=false)]
public partial class pickupNoticeStatus {
    
    private status statusField;
    
    private string occurrencedatetimeField;
    
    /// <remarks/>
    public status status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("occurrence-datetime")]
    public string occurrencedatetime {
        get {
            return this.occurrencedatetimeField;
        }
        set {
            this.occurrencedatetimeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.digipost.no/schema/datatypes")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://api.digipost.no/schema/datatypes", IsNullable=false)]
public partial class proof {
    
    private string authorizernameField;
    
    private string backgroundcolorField;
    
    private string issuedtimeField;
    
    private validPeriod validperiodField;
    
    private proofHolder proofholderField;
    
    private string titleField;
    
    private string proofidnameField;
    
    private string proofidvalueField;
    
    private info[] attributeField;
    
    private info[] infoField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("authorizer-name")]
    public string authorizername {
        get {
            return this.authorizernameField;
        }
        set {
            this.authorizernameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("background-color")]
    public string backgroundcolor {
        get {
            return this.backgroundcolorField;
        }
        set {
            this.backgroundcolorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("issued-time")]
    public string issuedtime {
        get {
            return this.issuedtimeField;
        }
        set {
            this.issuedtimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("valid-period")]
    public validPeriod validperiod {
        get {
            return this.validperiodField;
        }
        set {
            this.validperiodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("proof-holder")]
    public proofHolder proofholder {
        get {
            return this.proofholderField;
        }
        set {
            this.proofholderField = value;
        }
    }
    
    /// <remarks/>
    public string title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("proof-id-name")]
    public string proofidname {
        get {
            return this.proofidnameField;
        }
        set {
            this.proofidnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("proof-id-value")]
    public string proofidvalue {
        get {
            return this.proofidvalueField;
        }
        set {
            this.proofidvalueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("attribute")]
    public info[] attribute {
        get {
            return this.attributeField;
        }
        set {
            this.attributeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("info")]
    public info[] info {
        get {
            return this.infoField;
        }
        set {
            this.infoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.digipost.no/schema/datatypes")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://api.digipost.no/schema/datatypes", IsNullable=false)]
public partial class receipt {
    
    private string receiptIdField;
    
    private string receiptNumberField;
    
    private string purchaseTimeField;
    
    private string totalPriceField;
    
    private string totalVatField;
    
    private string currencyField;
    
    private string cashierField;
    
    private string registerField;
    
    private string merchantchainField;
    
    private string merchantnameField;
    
    private string merchantphonenumberField;
    
    private datatypeaddress merchantaddressField;
    
    private string orgnumberField;
    
    private barcode barcodeField;
    
    private payment[] paymentsField;
    
    private receiptLine[] itemsField;
    
    private taxiDetails taxiDetailsField;
    
    private customer customerField;
    
    private delivery deliveryField;
    
    private string ordernumberField;
    
    private string membershipnumberField;
    
    private string commentField;
    
    /// <remarks/>
    public string receiptId {
        get {
            return this.receiptIdField;
        }
        set {
            this.receiptIdField = value;
        }
    }
    
    /// <remarks/>
    public string receiptNumber {
        get {
            return this.receiptNumberField;
        }
        set {
            this.receiptNumberField = value;
        }
    }
    
    /// <remarks/>
    public string purchaseTime {
        get {
            return this.purchaseTimeField;
        }
        set {
            this.purchaseTimeField = value;
        }
    }
    
    /// <remarks/>
    public string totalPrice {
        get {
            return this.totalPriceField;
        }
        set {
            this.totalPriceField = value;
        }
    }
    
    /// <remarks/>
    public string totalVat {
        get {
            return this.totalVatField;
        }
        set {
            this.totalVatField = value;
        }
    }
    
    /// <remarks/>
    public string currency {
        get {
            return this.currencyField;
        }
        set {
            this.currencyField = value;
        }
    }
    
    /// <remarks/>
    public string cashier {
        get {
            return this.cashierField;
        }
        set {
            this.cashierField = value;
        }
    }
    
    /// <remarks/>
    public string register {
        get {
            return this.registerField;
        }
        set {
            this.registerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("merchant-chain")]
    public string merchantchain {
        get {
            return this.merchantchainField;
        }
        set {
            this.merchantchainField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("merchant-name")]
    public string merchantname {
        get {
            return this.merchantnameField;
        }
        set {
            this.merchantnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("merchant-phone-number")]
    public string merchantphonenumber {
        get {
            return this.merchantphonenumberField;
        }
        set {
            this.merchantphonenumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("merchant-address")]
    public datatypeaddress merchantaddress {
        get {
            return this.merchantaddressField;
        }
        set {
            this.merchantaddressField = value;
        }
    }
    
    /// <remarks/>
    public string orgnumber {
        get {
            return this.orgnumberField;
        }
        set {
            this.orgnumberField = value;
        }
    }
    
    /// <remarks/>
    public barcode barcode {
        get {
            return this.barcodeField;
        }
        set {
            this.barcodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("payments")]
    public payment[] payments {
        get {
            return this.paymentsField;
        }
        set {
            this.paymentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("items")]
    public receiptLine[] items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    public taxiDetails taxiDetails {
        get {
            return this.taxiDetailsField;
        }
        set {
            this.taxiDetailsField = value;
        }
    }
    
    /// <remarks/>
    public customer customer {
        get {
            return this.customerField;
        }
        set {
            this.customerField = value;
        }
    }
    
    /// <remarks/>
    public delivery delivery {
        get {
            return this.deliveryField;
        }
        set {
            this.deliveryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("order-number")]
    public string ordernumber {
        get {
            return this.ordernumberField;
        }
        set {
            this.ordernumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("membership-number")]
    public string membershipnumber {
        get {
            return this.membershipnumberField;
        }
        set {
            this.membershipnumberField = value;
        }
    }
    
    /// <remarks/>
    public string comment {
        get {
            return this.commentField;
        }
        set {
            this.commentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.digipost.no/schema/datatypes")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://api.digipost.no/schema/datatypes", IsNullable=false)]
public partial class signedDocument {
    
    private string documentissuerField;
    
    private string documentsubjectField;
    
    private string signingtimeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("document-issuer")]
    public string documentissuer {
        get {
            return this.documentissuerField;
        }
        set {
            this.documentissuerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("document-subject")]
    public string documentsubject {
        get {
            return this.documentsubjectField;
        }
        set {
            this.documentsubjectField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("signing-time")]
    public string signingtime {
        get {
            return this.signingtimeField;
        }
        set {
            this.signingtimeField = value;
        }
    }
}
