source 'https://rubygems.org'

require 'json'
require 'open-uri'
versions = JSON.parse(OpenURI.open_uri('https://pages.github.com/versions.json').read)

gem 'github-pages', versions['github-pages'], group: :jekyll_plugins
gem "webrick", "~> 1.8"
gem "faraday", "~> 2.0.1"
